/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Nomad.Client.Client.OpenAPIDateConverter;

namespace Nomad.Client.Model
{
    /// <summary>
    /// JobDispatchResponse
    /// </summary>
    [DataContract(Name = "JobDispatchResponse")]
    public partial class JobDispatchResponse : IEquatable<JobDispatchResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="JobDispatchResponse" /> class.
        /// </summary>
        /// <param name="dispatchedJobID">dispatchedJobID.</param>
        /// <param name="evalCreateIndex">evalCreateIndex.</param>
        /// <param name="evalID">evalID.</param>
        /// <param name="jobCreateIndex">jobCreateIndex.</param>
        /// <param name="lastIndex">lastIndex.</param>
        /// <param name="requestTime">requestTime.</param>
        public JobDispatchResponse(string dispatchedJobID = default(string), int evalCreateIndex = default(int), string evalID = default(string), int jobCreateIndex = default(int), int lastIndex = default(int), long requestTime = default(long))
        {
            this.DispatchedJobID = dispatchedJobID;
            this.EvalCreateIndex = evalCreateIndex;
            this.EvalID = evalID;
            this.JobCreateIndex = jobCreateIndex;
            this.LastIndex = lastIndex;
            this.RequestTime = requestTime;
        }

        /// <summary>
        /// Gets or Sets DispatchedJobID
        /// </summary>
        [DataMember(Name = "DispatchedJobID", EmitDefaultValue = false)]
        public string DispatchedJobID { get; set; }

        /// <summary>
        /// Gets or Sets EvalCreateIndex
        /// </summary>
        [DataMember(Name = "EvalCreateIndex", EmitDefaultValue = false)]
        public int EvalCreateIndex { get; set; }

        /// <summary>
        /// Gets or Sets EvalID
        /// </summary>
        [DataMember(Name = "EvalID", EmitDefaultValue = false)]
        public string EvalID { get; set; }

        /// <summary>
        /// Gets or Sets JobCreateIndex
        /// </summary>
        [DataMember(Name = "JobCreateIndex", EmitDefaultValue = false)]
        public int JobCreateIndex { get; set; }

        /// <summary>
        /// Gets or Sets LastIndex
        /// </summary>
        [DataMember(Name = "LastIndex", EmitDefaultValue = false)]
        public int LastIndex { get; set; }

        /// <summary>
        /// Gets or Sets RequestTime
        /// </summary>
        [DataMember(Name = "RequestTime", EmitDefaultValue = false)]
        public long RequestTime { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class JobDispatchResponse {\n");
            sb.Append("  DispatchedJobID: ").Append(DispatchedJobID).Append("\n");
            sb.Append("  EvalCreateIndex: ").Append(EvalCreateIndex).Append("\n");
            sb.Append("  EvalID: ").Append(EvalID).Append("\n");
            sb.Append("  JobCreateIndex: ").Append(JobCreateIndex).Append("\n");
            sb.Append("  LastIndex: ").Append(LastIndex).Append("\n");
            sb.Append("  RequestTime: ").Append(RequestTime).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as JobDispatchResponse);
        }

        /// <summary>
        /// Returns true if JobDispatchResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of JobDispatchResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(JobDispatchResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.DispatchedJobID == input.DispatchedJobID ||
                    (this.DispatchedJobID != null &&
                    this.DispatchedJobID.Equals(input.DispatchedJobID))
                ) && 
                (
                    this.EvalCreateIndex == input.EvalCreateIndex ||
                    this.EvalCreateIndex.Equals(input.EvalCreateIndex)
                ) && 
                (
                    this.EvalID == input.EvalID ||
                    (this.EvalID != null &&
                    this.EvalID.Equals(input.EvalID))
                ) && 
                (
                    this.JobCreateIndex == input.JobCreateIndex ||
                    this.JobCreateIndex.Equals(input.JobCreateIndex)
                ) && 
                (
                    this.LastIndex == input.LastIndex ||
                    this.LastIndex.Equals(input.LastIndex)
                ) && 
                (
                    this.RequestTime == input.RequestTime ||
                    this.RequestTime.Equals(input.RequestTime)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.DispatchedJobID != null)
                    hashCode = hashCode * 59 + this.DispatchedJobID.GetHashCode();
                hashCode = hashCode * 59 + this.EvalCreateIndex.GetHashCode();
                if (this.EvalID != null)
                    hashCode = hashCode * 59 + this.EvalID.GetHashCode();
                hashCode = hashCode * 59 + this.JobCreateIndex.GetHashCode();
                hashCode = hashCode * 59 + this.LastIndex.GetHashCode();
                hashCode = hashCode * 59 + this.RequestTime.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // EvalCreateIndex (int) maximum
            if(this.EvalCreateIndex > (int)384)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for EvalCreateIndex, must be a value less than or equal to 384.", new [] { "EvalCreateIndex" });
            }

            // EvalCreateIndex (int) minimum
            if(this.EvalCreateIndex < (int)0)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for EvalCreateIndex, must be a value greater than or equal to 0.", new [] { "EvalCreateIndex" });
            }

            // JobCreateIndex (int) maximum
            if(this.JobCreateIndex > (int)384)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for JobCreateIndex, must be a value less than or equal to 384.", new [] { "JobCreateIndex" });
            }

            // JobCreateIndex (int) minimum
            if(this.JobCreateIndex < (int)0)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for JobCreateIndex, must be a value greater than or equal to 0.", new [] { "JobCreateIndex" });
            }

            // LastIndex (int) maximum
            if(this.LastIndex > (int)384)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for LastIndex, must be a value less than or equal to 384.", new [] { "LastIndex" });
            }

            // LastIndex (int) minimum
            if(this.LastIndex < (int)0)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for LastIndex, must be a value greater than or equal to 0.", new [] { "LastIndex" });
            }

            yield break;
        }
    }

}
