/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Nomad.Client.Client.OpenAPIDateConverter;

namespace Nomad.Client.Model
{
    /// <summary>
    /// UpdateStrategy
    /// </summary>
    [DataContract(Name = "UpdateStrategy")]
    public partial class UpdateStrategy : IEquatable<UpdateStrategy>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateStrategy" /> class.
        /// </summary>
        /// <param name="autoPromote">autoPromote.</param>
        /// <param name="autoRevert">autoRevert.</param>
        /// <param name="canary">canary.</param>
        /// <param name="healthCheck">healthCheck.</param>
        /// <param name="healthyDeadline">healthyDeadline.</param>
        /// <param name="maxParallel">maxParallel.</param>
        /// <param name="minHealthyTime">minHealthyTime.</param>
        /// <param name="progressDeadline">progressDeadline.</param>
        /// <param name="stagger">stagger.</param>
        public UpdateStrategy(bool autoPromote = default(bool), bool autoRevert = default(bool), int canary = default(int), string healthCheck = default(string), long healthyDeadline = default(long), int maxParallel = default(int), long minHealthyTime = default(long), long progressDeadline = default(long), long stagger = default(long))
        {
            this.AutoPromote = autoPromote;
            this.AutoRevert = autoRevert;
            this.Canary = canary;
            this.HealthCheck = healthCheck;
            this.HealthyDeadline = healthyDeadline;
            this.MaxParallel = maxParallel;
            this.MinHealthyTime = minHealthyTime;
            this.ProgressDeadline = progressDeadline;
            this.Stagger = stagger;
        }

        /// <summary>
        /// Gets or Sets AutoPromote
        /// </summary>
        [DataMember(Name = "AutoPromote", EmitDefaultValue = true)]
        public bool AutoPromote { get; set; }

        /// <summary>
        /// Gets or Sets AutoRevert
        /// </summary>
        [DataMember(Name = "AutoRevert", EmitDefaultValue = true)]
        public bool AutoRevert { get; set; }

        /// <summary>
        /// Gets or Sets Canary
        /// </summary>
        [DataMember(Name = "Canary", EmitDefaultValue = false)]
        public int Canary { get; set; }

        /// <summary>
        /// Gets or Sets HealthCheck
        /// </summary>
        [DataMember(Name = "HealthCheck", EmitDefaultValue = false)]
        public string HealthCheck { get; set; }

        /// <summary>
        /// Gets or Sets HealthyDeadline
        /// </summary>
        [DataMember(Name = "HealthyDeadline", EmitDefaultValue = false)]
        public long HealthyDeadline { get; set; }

        /// <summary>
        /// Gets or Sets MaxParallel
        /// </summary>
        [DataMember(Name = "MaxParallel", EmitDefaultValue = false)]
        public int MaxParallel { get; set; }

        /// <summary>
        /// Gets or Sets MinHealthyTime
        /// </summary>
        [DataMember(Name = "MinHealthyTime", EmitDefaultValue = false)]
        public long MinHealthyTime { get; set; }

        /// <summary>
        /// Gets or Sets ProgressDeadline
        /// </summary>
        [DataMember(Name = "ProgressDeadline", EmitDefaultValue = false)]
        public long ProgressDeadline { get; set; }

        /// <summary>
        /// Gets or Sets Stagger
        /// </summary>
        [DataMember(Name = "Stagger", EmitDefaultValue = false)]
        public long Stagger { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UpdateStrategy {\n");
            sb.Append("  AutoPromote: ").Append(AutoPromote).Append("\n");
            sb.Append("  AutoRevert: ").Append(AutoRevert).Append("\n");
            sb.Append("  Canary: ").Append(Canary).Append("\n");
            sb.Append("  HealthCheck: ").Append(HealthCheck).Append("\n");
            sb.Append("  HealthyDeadline: ").Append(HealthyDeadline).Append("\n");
            sb.Append("  MaxParallel: ").Append(MaxParallel).Append("\n");
            sb.Append("  MinHealthyTime: ").Append(MinHealthyTime).Append("\n");
            sb.Append("  ProgressDeadline: ").Append(ProgressDeadline).Append("\n");
            sb.Append("  Stagger: ").Append(Stagger).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UpdateStrategy);
        }

        /// <summary>
        /// Returns true if UpdateStrategy instances are equal
        /// </summary>
        /// <param name="input">Instance of UpdateStrategy to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UpdateStrategy input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.AutoPromote == input.AutoPromote ||
                    this.AutoPromote.Equals(input.AutoPromote)
                ) && 
                (
                    this.AutoRevert == input.AutoRevert ||
                    this.AutoRevert.Equals(input.AutoRevert)
                ) && 
                (
                    this.Canary == input.Canary ||
                    this.Canary.Equals(input.Canary)
                ) && 
                (
                    this.HealthCheck == input.HealthCheck ||
                    (this.HealthCheck != null &&
                    this.HealthCheck.Equals(input.HealthCheck))
                ) && 
                (
                    this.HealthyDeadline == input.HealthyDeadline ||
                    this.HealthyDeadline.Equals(input.HealthyDeadline)
                ) && 
                (
                    this.MaxParallel == input.MaxParallel ||
                    this.MaxParallel.Equals(input.MaxParallel)
                ) && 
                (
                    this.MinHealthyTime == input.MinHealthyTime ||
                    this.MinHealthyTime.Equals(input.MinHealthyTime)
                ) && 
                (
                    this.ProgressDeadline == input.ProgressDeadline ||
                    this.ProgressDeadline.Equals(input.ProgressDeadline)
                ) && 
                (
                    this.Stagger == input.Stagger ||
                    this.Stagger.Equals(input.Stagger)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = hashCode * 59 + this.AutoPromote.GetHashCode();
                hashCode = hashCode * 59 + this.AutoRevert.GetHashCode();
                hashCode = hashCode * 59 + this.Canary.GetHashCode();
                if (this.HealthCheck != null)
                    hashCode = hashCode * 59 + this.HealthCheck.GetHashCode();
                hashCode = hashCode * 59 + this.HealthyDeadline.GetHashCode();
                hashCode = hashCode * 59 + this.MaxParallel.GetHashCode();
                hashCode = hashCode * 59 + this.MinHealthyTime.GetHashCode();
                hashCode = hashCode * 59 + this.ProgressDeadline.GetHashCode();
                hashCode = hashCode * 59 + this.Stagger.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
