/*
 * Nomad
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.nomadproject.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.nomadproject.client.models.ConsulGatewayProxy;
import io.nomadproject.client.models.ConsulIngressConfigEntry;
import io.nomadproject.client.models.ConsulTerminatingConfigEntry;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import io.nomadproject.client.JSON;

/**
 * ConsulGateway
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ConsulGateway {
  public static final String SERIALIZED_NAME_INGRESS = "Ingress";
  @SerializedName(SERIALIZED_NAME_INGRESS)
  private ConsulIngressConfigEntry ingress;

  public static final String SERIALIZED_NAME_MESH = "Mesh";
  @SerializedName(SERIALIZED_NAME_MESH)
  private Object mesh = null;

  public static final String SERIALIZED_NAME_PROXY = "Proxy";
  @SerializedName(SERIALIZED_NAME_PROXY)
  private ConsulGatewayProxy proxy;

  public static final String SERIALIZED_NAME_TERMINATING = "Terminating";
  @SerializedName(SERIALIZED_NAME_TERMINATING)
  private ConsulTerminatingConfigEntry terminating;

  public ConsulGateway() { 
  }

  public ConsulGateway ingress(ConsulIngressConfigEntry ingress) {
    
    this.ingress = ingress;
    return this;
  }

   /**
   * Get ingress
   * @return ingress
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ConsulIngressConfigEntry getIngress() {
    return ingress;
  }


  public void setIngress(ConsulIngressConfigEntry ingress) {
    this.ingress = ingress;
  }


  public ConsulGateway mesh(Object mesh) {
    
    this.mesh = mesh;
    return this;
  }

   /**
   * Get mesh
   * @return mesh
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getMesh() {
    return mesh;
  }


  public void setMesh(Object mesh) {
    this.mesh = mesh;
  }


  public ConsulGateway proxy(ConsulGatewayProxy proxy) {
    
    this.proxy = proxy;
    return this;
  }

   /**
   * Get proxy
   * @return proxy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ConsulGatewayProxy getProxy() {
    return proxy;
  }


  public void setProxy(ConsulGatewayProxy proxy) {
    this.proxy = proxy;
  }


  public ConsulGateway terminating(ConsulTerminatingConfigEntry terminating) {
    
    this.terminating = terminating;
    return this;
  }

   /**
   * Get terminating
   * @return terminating
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ConsulTerminatingConfigEntry getTerminating() {
    return terminating;
  }


  public void setTerminating(ConsulTerminatingConfigEntry terminating) {
    this.terminating = terminating;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConsulGateway consulGateway = (ConsulGateway) o;
    return Objects.equals(this.ingress, consulGateway.ingress) &&
        Objects.equals(this.mesh, consulGateway.mesh) &&
        Objects.equals(this.proxy, consulGateway.proxy) &&
        Objects.equals(this.terminating, consulGateway.terminating);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(ingress, mesh, proxy, terminating);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConsulGateway {\n");
    sb.append("    ingress: ").append(toIndentedString(ingress)).append("\n");
    sb.append("    mesh: ").append(toIndentedString(mesh)).append("\n");
    sb.append("    proxy: ").append(toIndentedString(proxy)).append("\n");
    sb.append("    terminating: ").append(toIndentedString(terminating)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("Ingress");
    openapiFields.add("Mesh");
    openapiFields.add("Proxy");
    openapiFields.add("Terminating");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ConsulGateway
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (ConsulGateway.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in ConsulGateway is not found in the empty JSON string", ConsulGateway.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!ConsulGateway.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ConsulGateway` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      // validate the optional field `Ingress`
      if (jsonObj.getAsJsonObject("Ingress") != null) {
        ConsulIngressConfigEntry.validateJsonObject(jsonObj.getAsJsonObject("Ingress"));
      }
      // validate the optional field `Proxy`
      if (jsonObj.getAsJsonObject("Proxy") != null) {
        ConsulGatewayProxy.validateJsonObject(jsonObj.getAsJsonObject("Proxy"));
      }
      // validate the optional field `Terminating`
      if (jsonObj.getAsJsonObject("Terminating") != null) {
        ConsulTerminatingConfigEntry.validateJsonObject(jsonObj.getAsJsonObject("Terminating"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ConsulGateway.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ConsulGateway' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ConsulGateway> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ConsulGateway.class));

       return (TypeAdapter<T>) new TypeAdapter<ConsulGateway>() {
           @Override
           public void write(JsonWriter out, ConsulGateway value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ConsulGateway read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ConsulGateway given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ConsulGateway
  * @throws IOException if the JSON string is invalid with respect to ConsulGateway
  */
  public static ConsulGateway fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ConsulGateway.class);
  }

 /**
  * Convert an instance of ConsulGateway to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

