/*
 * Nomad
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.nomadproject.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import io.nomadproject.client.JSON;

/**
 * EvaluationStub
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class EvaluationStub {
  public static final String SERIALIZED_NAME_BLOCKED_EVAL = "BlockedEval";
  @SerializedName(SERIALIZED_NAME_BLOCKED_EVAL)
  private String blockedEval;

  public static final String SERIALIZED_NAME_CREATE_INDEX = "CreateIndex";
  @SerializedName(SERIALIZED_NAME_CREATE_INDEX)
  private Integer createIndex;

  public static final String SERIALIZED_NAME_CREATE_TIME = "CreateTime";
  @SerializedName(SERIALIZED_NAME_CREATE_TIME)
  private Long createTime;

  public static final String SERIALIZED_NAME_DEPLOYMENT_I_D = "DeploymentID";
  @SerializedName(SERIALIZED_NAME_DEPLOYMENT_I_D)
  private String deploymentID;

  public static final String SERIALIZED_NAME_I_D = "ID";
  @SerializedName(SERIALIZED_NAME_I_D)
  private String ID;

  public static final String SERIALIZED_NAME_JOB_I_D = "JobID";
  @SerializedName(SERIALIZED_NAME_JOB_I_D)
  private String jobID;

  public static final String SERIALIZED_NAME_MODIFY_INDEX = "ModifyIndex";
  @SerializedName(SERIALIZED_NAME_MODIFY_INDEX)
  private Integer modifyIndex;

  public static final String SERIALIZED_NAME_MODIFY_TIME = "ModifyTime";
  @SerializedName(SERIALIZED_NAME_MODIFY_TIME)
  private Long modifyTime;

  public static final String SERIALIZED_NAME_NAMESPACE = "Namespace";
  @SerializedName(SERIALIZED_NAME_NAMESPACE)
  private String namespace;

  public static final String SERIALIZED_NAME_NEXT_EVAL = "NextEval";
  @SerializedName(SERIALIZED_NAME_NEXT_EVAL)
  private String nextEval;

  public static final String SERIALIZED_NAME_NODE_I_D = "NodeID";
  @SerializedName(SERIALIZED_NAME_NODE_I_D)
  private String nodeID;

  public static final String SERIALIZED_NAME_PREVIOUS_EVAL = "PreviousEval";
  @SerializedName(SERIALIZED_NAME_PREVIOUS_EVAL)
  private String previousEval;

  public static final String SERIALIZED_NAME_PRIORITY = "Priority";
  @SerializedName(SERIALIZED_NAME_PRIORITY)
  private Integer priority;

  public static final String SERIALIZED_NAME_STATUS = "Status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private String status;

  public static final String SERIALIZED_NAME_STATUS_DESCRIPTION = "StatusDescription";
  @SerializedName(SERIALIZED_NAME_STATUS_DESCRIPTION)
  private String statusDescription;

  public static final String SERIALIZED_NAME_TRIGGERED_BY = "TriggeredBy";
  @SerializedName(SERIALIZED_NAME_TRIGGERED_BY)
  private String triggeredBy;

  public static final String SERIALIZED_NAME_TYPE = "Type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private String type;

  public static final String SERIALIZED_NAME_WAIT_UNTIL = "WaitUntil";
  @SerializedName(SERIALIZED_NAME_WAIT_UNTIL)
  private OffsetDateTime waitUntil;

  public EvaluationStub() { 
  }

  public EvaluationStub blockedEval(String blockedEval) {
    
    this.blockedEval = blockedEval;
    return this;
  }

   /**
   * Get blockedEval
   * @return blockedEval
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getBlockedEval() {
    return blockedEval;
  }


  public void setBlockedEval(String blockedEval) {
    this.blockedEval = blockedEval;
  }


  public EvaluationStub createIndex(Integer createIndex) {
    
    this.createIndex = createIndex;
    return this;
  }

   /**
   * Get createIndex
   * minimum: 0
   * maximum: 384
   * @return createIndex
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getCreateIndex() {
    return createIndex;
  }


  public void setCreateIndex(Integer createIndex) {
    this.createIndex = createIndex;
  }


  public EvaluationStub createTime(Long createTime) {
    
    this.createTime = createTime;
    return this;
  }

   /**
   * Get createTime
   * @return createTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getCreateTime() {
    return createTime;
  }


  public void setCreateTime(Long createTime) {
    this.createTime = createTime;
  }


  public EvaluationStub deploymentID(String deploymentID) {
    
    this.deploymentID = deploymentID;
    return this;
  }

   /**
   * Get deploymentID
   * @return deploymentID
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDeploymentID() {
    return deploymentID;
  }


  public void setDeploymentID(String deploymentID) {
    this.deploymentID = deploymentID;
  }


  public EvaluationStub ID(String ID) {
    
    this.ID = ID;
    return this;
  }

   /**
   * Get ID
   * @return ID
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getID() {
    return ID;
  }


  public void setID(String ID) {
    this.ID = ID;
  }


  public EvaluationStub jobID(String jobID) {
    
    this.jobID = jobID;
    return this;
  }

   /**
   * Get jobID
   * @return jobID
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getJobID() {
    return jobID;
  }


  public void setJobID(String jobID) {
    this.jobID = jobID;
  }


  public EvaluationStub modifyIndex(Integer modifyIndex) {
    
    this.modifyIndex = modifyIndex;
    return this;
  }

   /**
   * Get modifyIndex
   * minimum: 0
   * maximum: 384
   * @return modifyIndex
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getModifyIndex() {
    return modifyIndex;
  }


  public void setModifyIndex(Integer modifyIndex) {
    this.modifyIndex = modifyIndex;
  }


  public EvaluationStub modifyTime(Long modifyTime) {
    
    this.modifyTime = modifyTime;
    return this;
  }

   /**
   * Get modifyTime
   * @return modifyTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getModifyTime() {
    return modifyTime;
  }


  public void setModifyTime(Long modifyTime) {
    this.modifyTime = modifyTime;
  }


  public EvaluationStub namespace(String namespace) {
    
    this.namespace = namespace;
    return this;
  }

   /**
   * Get namespace
   * @return namespace
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getNamespace() {
    return namespace;
  }


  public void setNamespace(String namespace) {
    this.namespace = namespace;
  }


  public EvaluationStub nextEval(String nextEval) {
    
    this.nextEval = nextEval;
    return this;
  }

   /**
   * Get nextEval
   * @return nextEval
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getNextEval() {
    return nextEval;
  }


  public void setNextEval(String nextEval) {
    this.nextEval = nextEval;
  }


  public EvaluationStub nodeID(String nodeID) {
    
    this.nodeID = nodeID;
    return this;
  }

   /**
   * Get nodeID
   * @return nodeID
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getNodeID() {
    return nodeID;
  }


  public void setNodeID(String nodeID) {
    this.nodeID = nodeID;
  }


  public EvaluationStub previousEval(String previousEval) {
    
    this.previousEval = previousEval;
    return this;
  }

   /**
   * Get previousEval
   * @return previousEval
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPreviousEval() {
    return previousEval;
  }


  public void setPreviousEval(String previousEval) {
    this.previousEval = previousEval;
  }


  public EvaluationStub priority(Integer priority) {
    
    this.priority = priority;
    return this;
  }

   /**
   * Get priority
   * @return priority
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getPriority() {
    return priority;
  }


  public void setPriority(Integer priority) {
    this.priority = priority;
  }


  public EvaluationStub status(String status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getStatus() {
    return status;
  }


  public void setStatus(String status) {
    this.status = status;
  }


  public EvaluationStub statusDescription(String statusDescription) {
    
    this.statusDescription = statusDescription;
    return this;
  }

   /**
   * Get statusDescription
   * @return statusDescription
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getStatusDescription() {
    return statusDescription;
  }


  public void setStatusDescription(String statusDescription) {
    this.statusDescription = statusDescription;
  }


  public EvaluationStub triggeredBy(String triggeredBy) {
    
    this.triggeredBy = triggeredBy;
    return this;
  }

   /**
   * Get triggeredBy
   * @return triggeredBy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTriggeredBy() {
    return triggeredBy;
  }


  public void setTriggeredBy(String triggeredBy) {
    this.triggeredBy = triggeredBy;
  }


  public EvaluationStub type(String type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getType() {
    return type;
  }


  public void setType(String type) {
    this.type = type;
  }


  public EvaluationStub waitUntil(OffsetDateTime waitUntil) {
    
    this.waitUntil = waitUntil;
    return this;
  }

   /**
   * Get waitUntil
   * @return waitUntil
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getWaitUntil() {
    return waitUntil;
  }


  public void setWaitUntil(OffsetDateTime waitUntil) {
    this.waitUntil = waitUntil;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EvaluationStub evaluationStub = (EvaluationStub) o;
    return Objects.equals(this.blockedEval, evaluationStub.blockedEval) &&
        Objects.equals(this.createIndex, evaluationStub.createIndex) &&
        Objects.equals(this.createTime, evaluationStub.createTime) &&
        Objects.equals(this.deploymentID, evaluationStub.deploymentID) &&
        Objects.equals(this.ID, evaluationStub.ID) &&
        Objects.equals(this.jobID, evaluationStub.jobID) &&
        Objects.equals(this.modifyIndex, evaluationStub.modifyIndex) &&
        Objects.equals(this.modifyTime, evaluationStub.modifyTime) &&
        Objects.equals(this.namespace, evaluationStub.namespace) &&
        Objects.equals(this.nextEval, evaluationStub.nextEval) &&
        Objects.equals(this.nodeID, evaluationStub.nodeID) &&
        Objects.equals(this.previousEval, evaluationStub.previousEval) &&
        Objects.equals(this.priority, evaluationStub.priority) &&
        Objects.equals(this.status, evaluationStub.status) &&
        Objects.equals(this.statusDescription, evaluationStub.statusDescription) &&
        Objects.equals(this.triggeredBy, evaluationStub.triggeredBy) &&
        Objects.equals(this.type, evaluationStub.type) &&
        Objects.equals(this.waitUntil, evaluationStub.waitUntil);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(blockedEval, createIndex, createTime, deploymentID, ID, jobID, modifyIndex, modifyTime, namespace, nextEval, nodeID, previousEval, priority, status, statusDescription, triggeredBy, type, waitUntil);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EvaluationStub {\n");
    sb.append("    blockedEval: ").append(toIndentedString(blockedEval)).append("\n");
    sb.append("    createIndex: ").append(toIndentedString(createIndex)).append("\n");
    sb.append("    createTime: ").append(toIndentedString(createTime)).append("\n");
    sb.append("    deploymentID: ").append(toIndentedString(deploymentID)).append("\n");
    sb.append("    ID: ").append(toIndentedString(ID)).append("\n");
    sb.append("    jobID: ").append(toIndentedString(jobID)).append("\n");
    sb.append("    modifyIndex: ").append(toIndentedString(modifyIndex)).append("\n");
    sb.append("    modifyTime: ").append(toIndentedString(modifyTime)).append("\n");
    sb.append("    namespace: ").append(toIndentedString(namespace)).append("\n");
    sb.append("    nextEval: ").append(toIndentedString(nextEval)).append("\n");
    sb.append("    nodeID: ").append(toIndentedString(nodeID)).append("\n");
    sb.append("    previousEval: ").append(toIndentedString(previousEval)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    statusDescription: ").append(toIndentedString(statusDescription)).append("\n");
    sb.append("    triggeredBy: ").append(toIndentedString(triggeredBy)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    waitUntil: ").append(toIndentedString(waitUntil)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("BlockedEval");
    openapiFields.add("CreateIndex");
    openapiFields.add("CreateTime");
    openapiFields.add("DeploymentID");
    openapiFields.add("ID");
    openapiFields.add("JobID");
    openapiFields.add("ModifyIndex");
    openapiFields.add("ModifyTime");
    openapiFields.add("Namespace");
    openapiFields.add("NextEval");
    openapiFields.add("NodeID");
    openapiFields.add("PreviousEval");
    openapiFields.add("Priority");
    openapiFields.add("Status");
    openapiFields.add("StatusDescription");
    openapiFields.add("TriggeredBy");
    openapiFields.add("Type");
    openapiFields.add("WaitUntil");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to EvaluationStub
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (EvaluationStub.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in EvaluationStub is not found in the empty JSON string", EvaluationStub.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!EvaluationStub.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `EvaluationStub` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if (jsonObj.get("BlockedEval") != null && !jsonObj.get("BlockedEval").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `BlockedEval` to be a primitive type in the JSON string but got `%s`", jsonObj.get("BlockedEval").toString()));
      }
      if (jsonObj.get("DeploymentID") != null && !jsonObj.get("DeploymentID").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `DeploymentID` to be a primitive type in the JSON string but got `%s`", jsonObj.get("DeploymentID").toString()));
      }
      if (jsonObj.get("ID") != null && !jsonObj.get("ID").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `ID` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ID").toString()));
      }
      if (jsonObj.get("JobID") != null && !jsonObj.get("JobID").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `JobID` to be a primitive type in the JSON string but got `%s`", jsonObj.get("JobID").toString()));
      }
      if (jsonObj.get("Namespace") != null && !jsonObj.get("Namespace").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `Namespace` to be a primitive type in the JSON string but got `%s`", jsonObj.get("Namespace").toString()));
      }
      if (jsonObj.get("NextEval") != null && !jsonObj.get("NextEval").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `NextEval` to be a primitive type in the JSON string but got `%s`", jsonObj.get("NextEval").toString()));
      }
      if (jsonObj.get("NodeID") != null && !jsonObj.get("NodeID").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `NodeID` to be a primitive type in the JSON string but got `%s`", jsonObj.get("NodeID").toString()));
      }
      if (jsonObj.get("PreviousEval") != null && !jsonObj.get("PreviousEval").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `PreviousEval` to be a primitive type in the JSON string but got `%s`", jsonObj.get("PreviousEval").toString()));
      }
      if (jsonObj.get("Status") != null && !jsonObj.get("Status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `Status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("Status").toString()));
      }
      if (jsonObj.get("StatusDescription") != null && !jsonObj.get("StatusDescription").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `StatusDescription` to be a primitive type in the JSON string but got `%s`", jsonObj.get("StatusDescription").toString()));
      }
      if (jsonObj.get("TriggeredBy") != null && !jsonObj.get("TriggeredBy").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `TriggeredBy` to be a primitive type in the JSON string but got `%s`", jsonObj.get("TriggeredBy").toString()));
      }
      if (jsonObj.get("Type") != null && !jsonObj.get("Type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `Type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("Type").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!EvaluationStub.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'EvaluationStub' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<EvaluationStub> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(EvaluationStub.class));

       return (TypeAdapter<T>) new TypeAdapter<EvaluationStub>() {
           @Override
           public void write(JsonWriter out, EvaluationStub value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public EvaluationStub read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of EvaluationStub given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of EvaluationStub
  * @throws IOException if the JSON string is invalid with respect to EvaluationStub
  */
  public static EvaluationStub fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, EvaluationStub.class);
  }

 /**
  * Convert an instance of EvaluationStub to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

