/*
 * Nomad
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.nomadproject.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * FuzzySearchRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class FuzzySearchRequest {
  public static final String SERIALIZED_NAME_ALLOW_STALE = "AllowStale";
  @SerializedName(SERIALIZED_NAME_ALLOW_STALE)
  private Boolean allowStale;

  public static final String SERIALIZED_NAME_AUTH_TOKEN = "AuthToken";
  @SerializedName(SERIALIZED_NAME_AUTH_TOKEN)
  private String authToken;

  public static final String SERIALIZED_NAME_CONTEXT = "Context";
  @SerializedName(SERIALIZED_NAME_CONTEXT)
  private String context;

  public static final String SERIALIZED_NAME_FILTER = "Filter";
  @SerializedName(SERIALIZED_NAME_FILTER)
  private String filter;

  public static final String SERIALIZED_NAME_HEADERS = "Headers";
  @SerializedName(SERIALIZED_NAME_HEADERS)
  private Map<String, String> headers = null;

  public static final String SERIALIZED_NAME_NAMESPACE = "Namespace";
  @SerializedName(SERIALIZED_NAME_NAMESPACE)
  private String namespace;

  public static final String SERIALIZED_NAME_NEXT_TOKEN = "NextToken";
  @SerializedName(SERIALIZED_NAME_NEXT_TOKEN)
  private String nextToken;

  public static final String SERIALIZED_NAME_PARAMS = "Params";
  @SerializedName(SERIALIZED_NAME_PARAMS)
  private Map<String, String> params = null;

  public static final String SERIALIZED_NAME_PER_PAGE = "PerPage";
  @SerializedName(SERIALIZED_NAME_PER_PAGE)
  private Integer perPage;

  public static final String SERIALIZED_NAME_PREFIX = "Prefix";
  @SerializedName(SERIALIZED_NAME_PREFIX)
  private String prefix;

  public static final String SERIALIZED_NAME_REGION = "Region";
  @SerializedName(SERIALIZED_NAME_REGION)
  private String region;

  public static final String SERIALIZED_NAME_REVERSE = "Reverse";
  @SerializedName(SERIALIZED_NAME_REVERSE)
  private Boolean reverse;

  public static final String SERIALIZED_NAME_TEXT = "Text";
  @SerializedName(SERIALIZED_NAME_TEXT)
  private String text;

  public static final String SERIALIZED_NAME_WAIT_INDEX = "WaitIndex";
  @SerializedName(SERIALIZED_NAME_WAIT_INDEX)
  private Integer waitIndex;

  public static final String SERIALIZED_NAME_WAIT_TIME = "WaitTime";
  @SerializedName(SERIALIZED_NAME_WAIT_TIME)
  private Long waitTime;


  public FuzzySearchRequest allowStale(Boolean allowStale) {
    
    this.allowStale = allowStale;
    return this;
  }

   /**
   * Get allowStale
   * @return allowStale
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getAllowStale() {
    return allowStale;
  }


  public void setAllowStale(Boolean allowStale) {
    this.allowStale = allowStale;
  }


  public FuzzySearchRequest authToken(String authToken) {
    
    this.authToken = authToken;
    return this;
  }

   /**
   * Get authToken
   * @return authToken
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getAuthToken() {
    return authToken;
  }


  public void setAuthToken(String authToken) {
    this.authToken = authToken;
  }


  public FuzzySearchRequest context(String context) {
    
    this.context = context;
    return this;
  }

   /**
   * Get context
   * @return context
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getContext() {
    return context;
  }


  public void setContext(String context) {
    this.context = context;
  }


  public FuzzySearchRequest filter(String filter) {
    
    this.filter = filter;
    return this;
  }

   /**
   * Get filter
   * @return filter
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getFilter() {
    return filter;
  }


  public void setFilter(String filter) {
    this.filter = filter;
  }


  public FuzzySearchRequest headers(Map<String, String> headers) {
    
    this.headers = headers;
    return this;
  }

  public FuzzySearchRequest putHeadersItem(String key, String headersItem) {
    if (this.headers == null) {
      this.headers = new HashMap<String, String>();
    }
    this.headers.put(key, headersItem);
    return this;
  }

   /**
   * Get headers
   * @return headers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Map<String, String> getHeaders() {
    return headers;
  }


  public void setHeaders(Map<String, String> headers) {
    this.headers = headers;
  }


  public FuzzySearchRequest namespace(String namespace) {
    
    this.namespace = namespace;
    return this;
  }

   /**
   * Get namespace
   * @return namespace
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getNamespace() {
    return namespace;
  }


  public void setNamespace(String namespace) {
    this.namespace = namespace;
  }


  public FuzzySearchRequest nextToken(String nextToken) {
    
    this.nextToken = nextToken;
    return this;
  }

   /**
   * Get nextToken
   * @return nextToken
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getNextToken() {
    return nextToken;
  }


  public void setNextToken(String nextToken) {
    this.nextToken = nextToken;
  }


  public FuzzySearchRequest params(Map<String, String> params) {
    
    this.params = params;
    return this;
  }

  public FuzzySearchRequest putParamsItem(String key, String paramsItem) {
    if (this.params == null) {
      this.params = new HashMap<String, String>();
    }
    this.params.put(key, paramsItem);
    return this;
  }

   /**
   * Get params
   * @return params
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Map<String, String> getParams() {
    return params;
  }


  public void setParams(Map<String, String> params) {
    this.params = params;
  }


  public FuzzySearchRequest perPage(Integer perPage) {
    
    this.perPage = perPage;
    return this;
  }

   /**
   * Get perPage
   * @return perPage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getPerPage() {
    return perPage;
  }


  public void setPerPage(Integer perPage) {
    this.perPage = perPage;
  }


  public FuzzySearchRequest prefix(String prefix) {
    
    this.prefix = prefix;
    return this;
  }

   /**
   * Get prefix
   * @return prefix
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPrefix() {
    return prefix;
  }


  public void setPrefix(String prefix) {
    this.prefix = prefix;
  }


  public FuzzySearchRequest region(String region) {
    
    this.region = region;
    return this;
  }

   /**
   * Get region
   * @return region
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getRegion() {
    return region;
  }


  public void setRegion(String region) {
    this.region = region;
  }


  public FuzzySearchRequest reverse(Boolean reverse) {
    
    this.reverse = reverse;
    return this;
  }

   /**
   * Get reverse
   * @return reverse
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getReverse() {
    return reverse;
  }


  public void setReverse(Boolean reverse) {
    this.reverse = reverse;
  }


  public FuzzySearchRequest text(String text) {
    
    this.text = text;
    return this;
  }

   /**
   * Get text
   * @return text
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getText() {
    return text;
  }


  public void setText(String text) {
    this.text = text;
  }


  public FuzzySearchRequest waitIndex(Integer waitIndex) {
    
    this.waitIndex = waitIndex;
    return this;
  }

   /**
   * Get waitIndex
   * minimum: 0
   * maximum: 384
   * @return waitIndex
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getWaitIndex() {
    return waitIndex;
  }


  public void setWaitIndex(Integer waitIndex) {
    this.waitIndex = waitIndex;
  }


  public FuzzySearchRequest waitTime(Long waitTime) {
    
    this.waitTime = waitTime;
    return this;
  }

   /**
   * Get waitTime
   * @return waitTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getWaitTime() {
    return waitTime;
  }


  public void setWaitTime(Long waitTime) {
    this.waitTime = waitTime;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FuzzySearchRequest fuzzySearchRequest = (FuzzySearchRequest) o;
    return Objects.equals(this.allowStale, fuzzySearchRequest.allowStale) &&
        Objects.equals(this.authToken, fuzzySearchRequest.authToken) &&
        Objects.equals(this.context, fuzzySearchRequest.context) &&
        Objects.equals(this.filter, fuzzySearchRequest.filter) &&
        Objects.equals(this.headers, fuzzySearchRequest.headers) &&
        Objects.equals(this.namespace, fuzzySearchRequest.namespace) &&
        Objects.equals(this.nextToken, fuzzySearchRequest.nextToken) &&
        Objects.equals(this.params, fuzzySearchRequest.params) &&
        Objects.equals(this.perPage, fuzzySearchRequest.perPage) &&
        Objects.equals(this.prefix, fuzzySearchRequest.prefix) &&
        Objects.equals(this.region, fuzzySearchRequest.region) &&
        Objects.equals(this.reverse, fuzzySearchRequest.reverse) &&
        Objects.equals(this.text, fuzzySearchRequest.text) &&
        Objects.equals(this.waitIndex, fuzzySearchRequest.waitIndex) &&
        Objects.equals(this.waitTime, fuzzySearchRequest.waitTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(allowStale, authToken, context, filter, headers, namespace, nextToken, params, perPage, prefix, region, reverse, text, waitIndex, waitTime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FuzzySearchRequest {\n");
    sb.append("    allowStale: ").append(toIndentedString(allowStale)).append("\n");
    sb.append("    authToken: ").append(toIndentedString(authToken)).append("\n");
    sb.append("    context: ").append(toIndentedString(context)).append("\n");
    sb.append("    filter: ").append(toIndentedString(filter)).append("\n");
    sb.append("    headers: ").append(toIndentedString(headers)).append("\n");
    sb.append("    namespace: ").append(toIndentedString(namespace)).append("\n");
    sb.append("    nextToken: ").append(toIndentedString(nextToken)).append("\n");
    sb.append("    params: ").append(toIndentedString(params)).append("\n");
    sb.append("    perPage: ").append(toIndentedString(perPage)).append("\n");
    sb.append("    prefix: ").append(toIndentedString(prefix)).append("\n");
    sb.append("    region: ").append(toIndentedString(region)).append("\n");
    sb.append("    reverse: ").append(toIndentedString(reverse)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    waitIndex: ").append(toIndentedString(waitIndex)).append("\n");
    sb.append("    waitTime: ").append(toIndentedString(waitTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

