/*
 * Nomad
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.nomadproject.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.nomadproject.client.models.SpreadTarget;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Spread
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class Spread {
  public static final String SERIALIZED_NAME_ATTRIBUTE = "Attribute";
  @SerializedName(SERIALIZED_NAME_ATTRIBUTE)
  private String attribute;

  public static final String SERIALIZED_NAME_SPREAD_TARGET = "SpreadTarget";
  @SerializedName(SERIALIZED_NAME_SPREAD_TARGET)
  private List<SpreadTarget> spreadTarget = null;

  public static final String SERIALIZED_NAME_WEIGHT = "Weight";
  @SerializedName(SERIALIZED_NAME_WEIGHT)
  private Integer weight;


  public Spread attribute(String attribute) {
    
    this.attribute = attribute;
    return this;
  }

   /**
   * Get attribute
   * @return attribute
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getAttribute() {
    return attribute;
  }


  public void setAttribute(String attribute) {
    this.attribute = attribute;
  }


  public Spread spreadTarget(List<SpreadTarget> spreadTarget) {
    
    this.spreadTarget = spreadTarget;
    return this;
  }

  public Spread addSpreadTargetItem(SpreadTarget spreadTargetItem) {
    if (this.spreadTarget == null) {
      this.spreadTarget = new ArrayList<SpreadTarget>();
    }
    this.spreadTarget.add(spreadTargetItem);
    return this;
  }

   /**
   * Get spreadTarget
   * @return spreadTarget
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<SpreadTarget> getSpreadTarget() {
    return spreadTarget;
  }


  public void setSpreadTarget(List<SpreadTarget> spreadTarget) {
    this.spreadTarget = spreadTarget;
  }


  public Spread weight(Integer weight) {
    
    this.weight = weight;
    return this;
  }

   /**
   * Get weight
   * minimum: -128
   * maximum: 127
   * @return weight
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getWeight() {
    return weight;
  }


  public void setWeight(Integer weight) {
    this.weight = weight;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Spread spread = (Spread) o;
    return Objects.equals(this.attribute, spread.attribute) &&
        Objects.equals(this.spreadTarget, spread.spreadTarget) &&
        Objects.equals(this.weight, spread.weight);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attribute, spreadTarget, weight);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Spread {\n");
    sb.append("    attribute: ").append(toIndentedString(attribute)).append("\n");
    sb.append("    spreadTarget: ").append(toIndentedString(spreadTarget)).append("\n");
    sb.append("    weight: ").append(toIndentedString(weight)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

