/*
 * Nomad
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.nomadproject.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import io.nomadproject.client.JSON;

/**
 * UpdateStrategy
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class UpdateStrategy {
  public static final String SERIALIZED_NAME_AUTO_PROMOTE = "AutoPromote";
  @SerializedName(SERIALIZED_NAME_AUTO_PROMOTE)
  private Boolean autoPromote;

  public static final String SERIALIZED_NAME_AUTO_REVERT = "AutoRevert";
  @SerializedName(SERIALIZED_NAME_AUTO_REVERT)
  private Boolean autoRevert;

  public static final String SERIALIZED_NAME_CANARY = "Canary";
  @SerializedName(SERIALIZED_NAME_CANARY)
  private Integer canary;

  public static final String SERIALIZED_NAME_HEALTH_CHECK = "HealthCheck";
  @SerializedName(SERIALIZED_NAME_HEALTH_CHECK)
  private String healthCheck;

  public static final String SERIALIZED_NAME_HEALTHY_DEADLINE = "HealthyDeadline";
  @SerializedName(SERIALIZED_NAME_HEALTHY_DEADLINE)
  private Long healthyDeadline;

  public static final String SERIALIZED_NAME_MAX_PARALLEL = "MaxParallel";
  @SerializedName(SERIALIZED_NAME_MAX_PARALLEL)
  private Integer maxParallel;

  public static final String SERIALIZED_NAME_MIN_HEALTHY_TIME = "MinHealthyTime";
  @SerializedName(SERIALIZED_NAME_MIN_HEALTHY_TIME)
  private Long minHealthyTime;

  public static final String SERIALIZED_NAME_PROGRESS_DEADLINE = "ProgressDeadline";
  @SerializedName(SERIALIZED_NAME_PROGRESS_DEADLINE)
  private Long progressDeadline;

  public static final String SERIALIZED_NAME_STAGGER = "Stagger";
  @SerializedName(SERIALIZED_NAME_STAGGER)
  private Long stagger;

  public UpdateStrategy() { 
  }

  public UpdateStrategy autoPromote(Boolean autoPromote) {
    
    this.autoPromote = autoPromote;
    return this;
  }

   /**
   * Get autoPromote
   * @return autoPromote
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getAutoPromote() {
    return autoPromote;
  }


  public void setAutoPromote(Boolean autoPromote) {
    this.autoPromote = autoPromote;
  }


  public UpdateStrategy autoRevert(Boolean autoRevert) {
    
    this.autoRevert = autoRevert;
    return this;
  }

   /**
   * Get autoRevert
   * @return autoRevert
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getAutoRevert() {
    return autoRevert;
  }


  public void setAutoRevert(Boolean autoRevert) {
    this.autoRevert = autoRevert;
  }


  public UpdateStrategy canary(Integer canary) {
    
    this.canary = canary;
    return this;
  }

   /**
   * Get canary
   * @return canary
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getCanary() {
    return canary;
  }


  public void setCanary(Integer canary) {
    this.canary = canary;
  }


  public UpdateStrategy healthCheck(String healthCheck) {
    
    this.healthCheck = healthCheck;
    return this;
  }

   /**
   * Get healthCheck
   * @return healthCheck
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getHealthCheck() {
    return healthCheck;
  }


  public void setHealthCheck(String healthCheck) {
    this.healthCheck = healthCheck;
  }


  public UpdateStrategy healthyDeadline(Long healthyDeadline) {
    
    this.healthyDeadline = healthyDeadline;
    return this;
  }

   /**
   * Get healthyDeadline
   * @return healthyDeadline
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getHealthyDeadline() {
    return healthyDeadline;
  }


  public void setHealthyDeadline(Long healthyDeadline) {
    this.healthyDeadline = healthyDeadline;
  }


  public UpdateStrategy maxParallel(Integer maxParallel) {
    
    this.maxParallel = maxParallel;
    return this;
  }

   /**
   * Get maxParallel
   * @return maxParallel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getMaxParallel() {
    return maxParallel;
  }


  public void setMaxParallel(Integer maxParallel) {
    this.maxParallel = maxParallel;
  }


  public UpdateStrategy minHealthyTime(Long minHealthyTime) {
    
    this.minHealthyTime = minHealthyTime;
    return this;
  }

   /**
   * Get minHealthyTime
   * @return minHealthyTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getMinHealthyTime() {
    return minHealthyTime;
  }


  public void setMinHealthyTime(Long minHealthyTime) {
    this.minHealthyTime = minHealthyTime;
  }


  public UpdateStrategy progressDeadline(Long progressDeadline) {
    
    this.progressDeadline = progressDeadline;
    return this;
  }

   /**
   * Get progressDeadline
   * @return progressDeadline
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getProgressDeadline() {
    return progressDeadline;
  }


  public void setProgressDeadline(Long progressDeadline) {
    this.progressDeadline = progressDeadline;
  }


  public UpdateStrategy stagger(Long stagger) {
    
    this.stagger = stagger;
    return this;
  }

   /**
   * Get stagger
   * @return stagger
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getStagger() {
    return stagger;
  }


  public void setStagger(Long stagger) {
    this.stagger = stagger;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateStrategy updateStrategy = (UpdateStrategy) o;
    return Objects.equals(this.autoPromote, updateStrategy.autoPromote) &&
        Objects.equals(this.autoRevert, updateStrategy.autoRevert) &&
        Objects.equals(this.canary, updateStrategy.canary) &&
        Objects.equals(this.healthCheck, updateStrategy.healthCheck) &&
        Objects.equals(this.healthyDeadline, updateStrategy.healthyDeadline) &&
        Objects.equals(this.maxParallel, updateStrategy.maxParallel) &&
        Objects.equals(this.minHealthyTime, updateStrategy.minHealthyTime) &&
        Objects.equals(this.progressDeadline, updateStrategy.progressDeadline) &&
        Objects.equals(this.stagger, updateStrategy.stagger);
  }

  @Override
  public int hashCode() {
    return Objects.hash(autoPromote, autoRevert, canary, healthCheck, healthyDeadline, maxParallel, minHealthyTime, progressDeadline, stagger);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateStrategy {\n");
    sb.append("    autoPromote: ").append(toIndentedString(autoPromote)).append("\n");
    sb.append("    autoRevert: ").append(toIndentedString(autoRevert)).append("\n");
    sb.append("    canary: ").append(toIndentedString(canary)).append("\n");
    sb.append("    healthCheck: ").append(toIndentedString(healthCheck)).append("\n");
    sb.append("    healthyDeadline: ").append(toIndentedString(healthyDeadline)).append("\n");
    sb.append("    maxParallel: ").append(toIndentedString(maxParallel)).append("\n");
    sb.append("    minHealthyTime: ").append(toIndentedString(minHealthyTime)).append("\n");
    sb.append("    progressDeadline: ").append(toIndentedString(progressDeadline)).append("\n");
    sb.append("    stagger: ").append(toIndentedString(stagger)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("AutoPromote");
    openapiFields.add("AutoRevert");
    openapiFields.add("Canary");
    openapiFields.add("HealthCheck");
    openapiFields.add("HealthyDeadline");
    openapiFields.add("MaxParallel");
    openapiFields.add("MinHealthyTime");
    openapiFields.add("ProgressDeadline");
    openapiFields.add("Stagger");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to UpdateStrategy
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (UpdateStrategy.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in UpdateStrategy is not found in the empty JSON string", UpdateStrategy.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!UpdateStrategy.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `UpdateStrategy` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if (jsonObj.get("HealthCheck") != null && !jsonObj.get("HealthCheck").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `HealthCheck` to be a primitive type in the JSON string but got `%s`", jsonObj.get("HealthCheck").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UpdateStrategy.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UpdateStrategy' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UpdateStrategy> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UpdateStrategy.class));

       return (TypeAdapter<T>) new TypeAdapter<UpdateStrategy>() {
           @Override
           public void write(JsonWriter out, UpdateStrategy value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public UpdateStrategy read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of UpdateStrategy given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of UpdateStrategy
  * @throws IOException if the JSON string is invalid with respect to UpdateStrategy
  */
  public static UpdateStrategy fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UpdateStrategy.class);
  }

 /**
  * Convert an instance of UpdateStrategy to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

