/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Nomad.Client.Client;
using Nomad.Client.Model;

namespace Nomad.Client.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMetricsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Nomad.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="format">The format the user requested for the metrics summary (e.g. prometheus) (optional)</param>
        /// <returns>MetricsSummary</returns>
        MetricsSummary GetMetricsSummary(string format = default(string));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Nomad.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="format">The format the user requested for the metrics summary (e.g. prometheus) (optional)</param>
        /// <returns>ApiResponse of MetricsSummary</returns>
        ApiResponse<MetricsSummary> GetMetricsSummaryWithHttpInfo(string format = default(string));
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMetricsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Nomad.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="format">The format the user requested for the metrics summary (e.g. prometheus) (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of MetricsSummary</returns>
        System.Threading.Tasks.Task<MetricsSummary> GetMetricsSummaryAsync(string format = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Nomad.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="format">The format the user requested for the metrics summary (e.g. prometheus) (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (MetricsSummary)</returns>
        System.Threading.Tasks.Task<ApiResponse<MetricsSummary>> GetMetricsSummaryWithHttpInfoAsync(string format = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMetricsApi : IMetricsApiSync, IMetricsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class MetricsApi : IMetricsApi
    {
        private Nomad.Client.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="MetricsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public MetricsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MetricsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public MetricsApi(string basePath)
        {
            this.Configuration = Nomad.Client.Client.Configuration.MergeConfigurations(
                Nomad.Client.Client.GlobalConfiguration.Instance,
                new Nomad.Client.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Nomad.Client.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Nomad.Client.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Nomad.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MetricsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public MetricsApi(Nomad.Client.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Nomad.Client.Client.Configuration.MergeConfigurations(
                Nomad.Client.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Nomad.Client.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Nomad.Client.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Nomad.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MetricsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public MetricsApi(Nomad.Client.Client.ISynchronousClient client, Nomad.Client.Client.IAsynchronousClient asyncClient, Nomad.Client.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Nomad.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Nomad.Client.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Nomad.Client.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Nomad.Client.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Nomad.Client.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Nomad.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="format">The format the user requested for the metrics summary (e.g. prometheus) (optional)</param>
        /// <returns>MetricsSummary</returns>
        public MetricsSummary GetMetricsSummary(string format = default(string))
        {
            Nomad.Client.Client.ApiResponse<MetricsSummary> localVarResponse = GetMetricsSummaryWithHttpInfo(format);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Nomad.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="format">The format the user requested for the metrics summary (e.g. prometheus) (optional)</param>
        /// <returns>ApiResponse of MetricsSummary</returns>
        public Nomad.Client.Client.ApiResponse<MetricsSummary> GetMetricsSummaryWithHttpInfo(string format = default(string))
        {
            Nomad.Client.Client.RequestOptions localVarRequestOptions = new Nomad.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Nomad.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Nomad.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (format != null)
            {
                localVarRequestOptions.QueryParameters.Add(Nomad.Client.Client.ClientUtils.ParameterToMultiMap("", "format", format));
            }

            // authentication (X-Nomad-Token) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Nomad-Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-Nomad-Token", this.Configuration.GetApiKeyWithPrefix("X-Nomad-Token"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<MetricsSummary>("/metrics", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetMetricsSummary", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Nomad.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="format">The format the user requested for the metrics summary (e.g. prometheus) (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of MetricsSummary</returns>
        public async System.Threading.Tasks.Task<MetricsSummary> GetMetricsSummaryAsync(string format = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Nomad.Client.Client.ApiResponse<MetricsSummary> localVarResponse = await GetMetricsSummaryWithHttpInfoAsync(format, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Nomad.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="format">The format the user requested for the metrics summary (e.g. prometheus) (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (MetricsSummary)</returns>
        public async System.Threading.Tasks.Task<Nomad.Client.Client.ApiResponse<MetricsSummary>> GetMetricsSummaryWithHttpInfoAsync(string format = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Nomad.Client.Client.RequestOptions localVarRequestOptions = new Nomad.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Nomad.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Nomad.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (format != null)
            {
                localVarRequestOptions.QueryParameters.Add(Nomad.Client.Client.ClientUtils.ParameterToMultiMap("", "format", format));
            }

            // authentication (X-Nomad-Token) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Nomad-Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-Nomad-Token", this.Configuration.GetApiKeyWithPrefix("X-Nomad-Token"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<MetricsSummary>("/metrics", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetMetricsSummary", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
