/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Nomad.Client.Client;
using Nomad.Client.Model;

namespace Nomad.Client.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface INamespacesApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Nomad.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="region">Filters results based on the specified region. (optional)</param>
        /// <param name="_namespace">Filters results based on the specified namespace. (optional)</param>
        /// <param name="xNomadToken">A Nomad ACL token. (optional)</param>
        /// <param name="idempotencyToken">Can be used to ensure operations are only run once. (optional)</param>
        /// <returns></returns>
        void CreateNamespace(string region = default(string), string _namespace = default(string), string xNomadToken = default(string), string idempotencyToken = default(string));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Nomad.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="region">Filters results based on the specified region. (optional)</param>
        /// <param name="_namespace">Filters results based on the specified namespace. (optional)</param>
        /// <param name="xNomadToken">A Nomad ACL token. (optional)</param>
        /// <param name="idempotencyToken">Can be used to ensure operations are only run once. (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> CreateNamespaceWithHttpInfo(string region = default(string), string _namespace = default(string), string xNomadToken = default(string), string idempotencyToken = default(string));
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Nomad.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="namespaceName">The namespace identifier.</param>
        /// <param name="region">Filters results based on the specified region. (optional)</param>
        /// <param name="_namespace">Filters results based on the specified namespace. (optional)</param>
        /// <param name="xNomadToken">A Nomad ACL token. (optional)</param>
        /// <param name="idempotencyToken">Can be used to ensure operations are only run once. (optional)</param>
        /// <returns></returns>
        void DeleteNamespace(string namespaceName, string region = default(string), string _namespace = default(string), string xNomadToken = default(string), string idempotencyToken = default(string));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Nomad.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="namespaceName">The namespace identifier.</param>
        /// <param name="region">Filters results based on the specified region. (optional)</param>
        /// <param name="_namespace">Filters results based on the specified namespace. (optional)</param>
        /// <param name="xNomadToken">A Nomad ACL token. (optional)</param>
        /// <param name="idempotencyToken">Can be used to ensure operations are only run once. (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> DeleteNamespaceWithHttpInfo(string namespaceName, string region = default(string), string _namespace = default(string), string xNomadToken = default(string), string idempotencyToken = default(string));
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Nomad.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="namespaceName">The namespace identifier.</param>
        /// <param name="region">Filters results based on the specified region. (optional)</param>
        /// <param name="_namespace">Filters results based on the specified namespace. (optional)</param>
        /// <param name="index">If set, wait until query exceeds given index. Must be provided with WaitParam. (optional)</param>
        /// <param name="wait">Provided with IndexParam to wait for change. (optional)</param>
        /// <param name="stale">If present, results will include stale reads. (optional)</param>
        /// <param name="prefix">Constrains results to jobs that start with the defined prefix (optional)</param>
        /// <param name="xNomadToken">A Nomad ACL token. (optional)</param>
        /// <param name="perPage">Maximum number of results to return. (optional)</param>
        /// <param name="nextToken">Indicates where to start paging for queries that support pagination. (optional)</param>
        /// <returns>Namespace</returns>
        Namespace GetNamespace(string namespaceName, string region = default(string), string _namespace = default(string), int? index = default(int?), string wait = default(string), string stale = default(string), string prefix = default(string), string xNomadToken = default(string), int? perPage = default(int?), string nextToken = default(string));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Nomad.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="namespaceName">The namespace identifier.</param>
        /// <param name="region">Filters results based on the specified region. (optional)</param>
        /// <param name="_namespace">Filters results based on the specified namespace. (optional)</param>
        /// <param name="index">If set, wait until query exceeds given index. Must be provided with WaitParam. (optional)</param>
        /// <param name="wait">Provided with IndexParam to wait for change. (optional)</param>
        /// <param name="stale">If present, results will include stale reads. (optional)</param>
        /// <param name="prefix">Constrains results to jobs that start with the defined prefix (optional)</param>
        /// <param name="xNomadToken">A Nomad ACL token. (optional)</param>
        /// <param name="perPage">Maximum number of results to return. (optional)</param>
        /// <param name="nextToken">Indicates where to start paging for queries that support pagination. (optional)</param>
        /// <returns>ApiResponse of Namespace</returns>
        ApiResponse<Namespace> GetNamespaceWithHttpInfo(string namespaceName, string region = default(string), string _namespace = default(string), int? index = default(int?), string wait = default(string), string stale = default(string), string prefix = default(string), string xNomadToken = default(string), int? perPage = default(int?), string nextToken = default(string));
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Nomad.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="region">Filters results based on the specified region. (optional)</param>
        /// <param name="_namespace">Filters results based on the specified namespace. (optional)</param>
        /// <param name="index">If set, wait until query exceeds given index. Must be provided with WaitParam. (optional)</param>
        /// <param name="wait">Provided with IndexParam to wait for change. (optional)</param>
        /// <param name="stale">If present, results will include stale reads. (optional)</param>
        /// <param name="prefix">Constrains results to jobs that start with the defined prefix (optional)</param>
        /// <param name="xNomadToken">A Nomad ACL token. (optional)</param>
        /// <param name="perPage">Maximum number of results to return. (optional)</param>
        /// <param name="nextToken">Indicates where to start paging for queries that support pagination. (optional)</param>
        /// <returns>List&lt;Namespace&gt;</returns>
        List<Namespace> GetNamespaces(string region = default(string), string _namespace = default(string), int? index = default(int?), string wait = default(string), string stale = default(string), string prefix = default(string), string xNomadToken = default(string), int? perPage = default(int?), string nextToken = default(string));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Nomad.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="region">Filters results based on the specified region. (optional)</param>
        /// <param name="_namespace">Filters results based on the specified namespace. (optional)</param>
        /// <param name="index">If set, wait until query exceeds given index. Must be provided with WaitParam. (optional)</param>
        /// <param name="wait">Provided with IndexParam to wait for change. (optional)</param>
        /// <param name="stale">If present, results will include stale reads. (optional)</param>
        /// <param name="prefix">Constrains results to jobs that start with the defined prefix (optional)</param>
        /// <param name="xNomadToken">A Nomad ACL token. (optional)</param>
        /// <param name="perPage">Maximum number of results to return. (optional)</param>
        /// <param name="nextToken">Indicates where to start paging for queries that support pagination. (optional)</param>
        /// <returns>ApiResponse of List&lt;Namespace&gt;</returns>
        ApiResponse<List<Namespace>> GetNamespacesWithHttpInfo(string region = default(string), string _namespace = default(string), int? index = default(int?), string wait = default(string), string stale = default(string), string prefix = default(string), string xNomadToken = default(string), int? perPage = default(int?), string nextToken = default(string));
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Nomad.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="namespaceName">The namespace identifier.</param>
        /// <param name="_namespace2"></param>
        /// <param name="region">Filters results based on the specified region. (optional)</param>
        /// <param name="_namespace">Filters results based on the specified namespace. (optional)</param>
        /// <param name="xNomadToken">A Nomad ACL token. (optional)</param>
        /// <param name="idempotencyToken">Can be used to ensure operations are only run once. (optional)</param>
        /// <returns></returns>
        void PostNamespace(string namespaceName, Namespace _namespace2, string region = default(string), string _namespace = default(string), string xNomadToken = default(string), string idempotencyToken = default(string));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Nomad.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="namespaceName">The namespace identifier.</param>
        /// <param name="_namespace2"></param>
        /// <param name="region">Filters results based on the specified region. (optional)</param>
        /// <param name="_namespace">Filters results based on the specified namespace. (optional)</param>
        /// <param name="xNomadToken">A Nomad ACL token. (optional)</param>
        /// <param name="idempotencyToken">Can be used to ensure operations are only run once. (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> PostNamespaceWithHttpInfo(string namespaceName, Namespace _namespace2, string region = default(string), string _namespace = default(string), string xNomadToken = default(string), string idempotencyToken = default(string));
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface INamespacesApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Nomad.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="region">Filters results based on the specified region. (optional)</param>
        /// <param name="_namespace">Filters results based on the specified namespace. (optional)</param>
        /// <param name="xNomadToken">A Nomad ACL token. (optional)</param>
        /// <param name="idempotencyToken">Can be used to ensure operations are only run once. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task CreateNamespaceAsync(string region = default(string), string _namespace = default(string), string xNomadToken = default(string), string idempotencyToken = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Nomad.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="region">Filters results based on the specified region. (optional)</param>
        /// <param name="_namespace">Filters results based on the specified namespace. (optional)</param>
        /// <param name="xNomadToken">A Nomad ACL token. (optional)</param>
        /// <param name="idempotencyToken">Can be used to ensure operations are only run once. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> CreateNamespaceWithHttpInfoAsync(string region = default(string), string _namespace = default(string), string xNomadToken = default(string), string idempotencyToken = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Nomad.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="namespaceName">The namespace identifier.</param>
        /// <param name="region">Filters results based on the specified region. (optional)</param>
        /// <param name="_namespace">Filters results based on the specified namespace. (optional)</param>
        /// <param name="xNomadToken">A Nomad ACL token. (optional)</param>
        /// <param name="idempotencyToken">Can be used to ensure operations are only run once. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task DeleteNamespaceAsync(string namespaceName, string region = default(string), string _namespace = default(string), string xNomadToken = default(string), string idempotencyToken = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Nomad.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="namespaceName">The namespace identifier.</param>
        /// <param name="region">Filters results based on the specified region. (optional)</param>
        /// <param name="_namespace">Filters results based on the specified namespace. (optional)</param>
        /// <param name="xNomadToken">A Nomad ACL token. (optional)</param>
        /// <param name="idempotencyToken">Can be used to ensure operations are only run once. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> DeleteNamespaceWithHttpInfoAsync(string namespaceName, string region = default(string), string _namespace = default(string), string xNomadToken = default(string), string idempotencyToken = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Nomad.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="namespaceName">The namespace identifier.</param>
        /// <param name="region">Filters results based on the specified region. (optional)</param>
        /// <param name="_namespace">Filters results based on the specified namespace. (optional)</param>
        /// <param name="index">If set, wait until query exceeds given index. Must be provided with WaitParam. (optional)</param>
        /// <param name="wait">Provided with IndexParam to wait for change. (optional)</param>
        /// <param name="stale">If present, results will include stale reads. (optional)</param>
        /// <param name="prefix">Constrains results to jobs that start with the defined prefix (optional)</param>
        /// <param name="xNomadToken">A Nomad ACL token. (optional)</param>
        /// <param name="perPage">Maximum number of results to return. (optional)</param>
        /// <param name="nextToken">Indicates where to start paging for queries that support pagination. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Namespace</returns>
        System.Threading.Tasks.Task<Namespace> GetNamespaceAsync(string namespaceName, string region = default(string), string _namespace = default(string), int? index = default(int?), string wait = default(string), string stale = default(string), string prefix = default(string), string xNomadToken = default(string), int? perPage = default(int?), string nextToken = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Nomad.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="namespaceName">The namespace identifier.</param>
        /// <param name="region">Filters results based on the specified region. (optional)</param>
        /// <param name="_namespace">Filters results based on the specified namespace. (optional)</param>
        /// <param name="index">If set, wait until query exceeds given index. Must be provided with WaitParam. (optional)</param>
        /// <param name="wait">Provided with IndexParam to wait for change. (optional)</param>
        /// <param name="stale">If present, results will include stale reads. (optional)</param>
        /// <param name="prefix">Constrains results to jobs that start with the defined prefix (optional)</param>
        /// <param name="xNomadToken">A Nomad ACL token. (optional)</param>
        /// <param name="perPage">Maximum number of results to return. (optional)</param>
        /// <param name="nextToken">Indicates where to start paging for queries that support pagination. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Namespace)</returns>
        System.Threading.Tasks.Task<ApiResponse<Namespace>> GetNamespaceWithHttpInfoAsync(string namespaceName, string region = default(string), string _namespace = default(string), int? index = default(int?), string wait = default(string), string stale = default(string), string prefix = default(string), string xNomadToken = default(string), int? perPage = default(int?), string nextToken = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Nomad.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="region">Filters results based on the specified region. (optional)</param>
        /// <param name="_namespace">Filters results based on the specified namespace. (optional)</param>
        /// <param name="index">If set, wait until query exceeds given index. Must be provided with WaitParam. (optional)</param>
        /// <param name="wait">Provided with IndexParam to wait for change. (optional)</param>
        /// <param name="stale">If present, results will include stale reads. (optional)</param>
        /// <param name="prefix">Constrains results to jobs that start with the defined prefix (optional)</param>
        /// <param name="xNomadToken">A Nomad ACL token. (optional)</param>
        /// <param name="perPage">Maximum number of results to return. (optional)</param>
        /// <param name="nextToken">Indicates where to start paging for queries that support pagination. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;Namespace&gt;</returns>
        System.Threading.Tasks.Task<List<Namespace>> GetNamespacesAsync(string region = default(string), string _namespace = default(string), int? index = default(int?), string wait = default(string), string stale = default(string), string prefix = default(string), string xNomadToken = default(string), int? perPage = default(int?), string nextToken = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Nomad.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="region">Filters results based on the specified region. (optional)</param>
        /// <param name="_namespace">Filters results based on the specified namespace. (optional)</param>
        /// <param name="index">If set, wait until query exceeds given index. Must be provided with WaitParam. (optional)</param>
        /// <param name="wait">Provided with IndexParam to wait for change. (optional)</param>
        /// <param name="stale">If present, results will include stale reads. (optional)</param>
        /// <param name="prefix">Constrains results to jobs that start with the defined prefix (optional)</param>
        /// <param name="xNomadToken">A Nomad ACL token. (optional)</param>
        /// <param name="perPage">Maximum number of results to return. (optional)</param>
        /// <param name="nextToken">Indicates where to start paging for queries that support pagination. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;Namespace&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<Namespace>>> GetNamespacesWithHttpInfoAsync(string region = default(string), string _namespace = default(string), int? index = default(int?), string wait = default(string), string stale = default(string), string prefix = default(string), string xNomadToken = default(string), int? perPage = default(int?), string nextToken = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Nomad.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="namespaceName">The namespace identifier.</param>
        /// <param name="_namespace2"></param>
        /// <param name="region">Filters results based on the specified region. (optional)</param>
        /// <param name="_namespace">Filters results based on the specified namespace. (optional)</param>
        /// <param name="xNomadToken">A Nomad ACL token. (optional)</param>
        /// <param name="idempotencyToken">Can be used to ensure operations are only run once. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task PostNamespaceAsync(string namespaceName, Namespace _namespace2, string region = default(string), string _namespace = default(string), string xNomadToken = default(string), string idempotencyToken = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Nomad.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="namespaceName">The namespace identifier.</param>
        /// <param name="_namespace2"></param>
        /// <param name="region">Filters results based on the specified region. (optional)</param>
        /// <param name="_namespace">Filters results based on the specified namespace. (optional)</param>
        /// <param name="xNomadToken">A Nomad ACL token. (optional)</param>
        /// <param name="idempotencyToken">Can be used to ensure operations are only run once. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> PostNamespaceWithHttpInfoAsync(string namespaceName, Namespace _namespace2, string region = default(string), string _namespace = default(string), string xNomadToken = default(string), string idempotencyToken = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface INamespacesApi : INamespacesApiSync, INamespacesApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class NamespacesApi : INamespacesApi
    {
        private Nomad.Client.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="NamespacesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public NamespacesApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NamespacesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public NamespacesApi(string basePath)
        {
            this.Configuration = Nomad.Client.Client.Configuration.MergeConfigurations(
                Nomad.Client.Client.GlobalConfiguration.Instance,
                new Nomad.Client.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Nomad.Client.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Nomad.Client.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Nomad.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NamespacesApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public NamespacesApi(Nomad.Client.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Nomad.Client.Client.Configuration.MergeConfigurations(
                Nomad.Client.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Nomad.Client.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Nomad.Client.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Nomad.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NamespacesApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public NamespacesApi(Nomad.Client.Client.ISynchronousClient client, Nomad.Client.Client.IAsynchronousClient asyncClient, Nomad.Client.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Nomad.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Nomad.Client.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Nomad.Client.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Nomad.Client.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Nomad.Client.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Nomad.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="region">Filters results based on the specified region. (optional)</param>
        /// <param name="_namespace">Filters results based on the specified namespace. (optional)</param>
        /// <param name="xNomadToken">A Nomad ACL token. (optional)</param>
        /// <param name="idempotencyToken">Can be used to ensure operations are only run once. (optional)</param>
        /// <returns></returns>
        public void CreateNamespace(string region = default(string), string _namespace = default(string), string xNomadToken = default(string), string idempotencyToken = default(string))
        {
            CreateNamespaceWithHttpInfo(region, _namespace, xNomadToken, idempotencyToken);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Nomad.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="region">Filters results based on the specified region. (optional)</param>
        /// <param name="_namespace">Filters results based on the specified namespace. (optional)</param>
        /// <param name="xNomadToken">A Nomad ACL token. (optional)</param>
        /// <param name="idempotencyToken">Can be used to ensure operations are only run once. (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public Nomad.Client.Client.ApiResponse<Object> CreateNamespaceWithHttpInfo(string region = default(string), string _namespace = default(string), string xNomadToken = default(string), string idempotencyToken = default(string))
        {
            Nomad.Client.Client.RequestOptions localVarRequestOptions = new Nomad.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };

            var localVarContentType = Nomad.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Nomad.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (region != null)
            {
                localVarRequestOptions.QueryParameters.Add(Nomad.Client.Client.ClientUtils.ParameterToMultiMap("", "region", region));
            }
            if (_namespace != null)
            {
                localVarRequestOptions.QueryParameters.Add(Nomad.Client.Client.ClientUtils.ParameterToMultiMap("", "namespace", _namespace));
            }
            if (idempotencyToken != null)
            {
                localVarRequestOptions.QueryParameters.Add(Nomad.Client.Client.ClientUtils.ParameterToMultiMap("", "idempotency_token", idempotencyToken));
            }
            if (xNomadToken != null)
            {
                localVarRequestOptions.HeaderParameters.Add("X-Nomad-Token", Nomad.Client.Client.ClientUtils.ParameterToString(xNomadToken)); // header parameter
            }

            // authentication (X-Nomad-Token) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Nomad-Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-Nomad-Token", this.Configuration.GetApiKeyWithPrefix("X-Nomad-Token"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<Object>("/namespace", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateNamespace", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Nomad.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="region">Filters results based on the specified region. (optional)</param>
        /// <param name="_namespace">Filters results based on the specified namespace. (optional)</param>
        /// <param name="xNomadToken">A Nomad ACL token. (optional)</param>
        /// <param name="idempotencyToken">Can be used to ensure operations are only run once. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task CreateNamespaceAsync(string region = default(string), string _namespace = default(string), string xNomadToken = default(string), string idempotencyToken = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            await CreateNamespaceWithHttpInfoAsync(region, _namespace, xNomadToken, idempotencyToken, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Nomad.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="region">Filters results based on the specified region. (optional)</param>
        /// <param name="_namespace">Filters results based on the specified namespace. (optional)</param>
        /// <param name="xNomadToken">A Nomad ACL token. (optional)</param>
        /// <param name="idempotencyToken">Can be used to ensure operations are only run once. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Nomad.Client.Client.ApiResponse<Object>> CreateNamespaceWithHttpInfoAsync(string region = default(string), string _namespace = default(string), string xNomadToken = default(string), string idempotencyToken = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Nomad.Client.Client.RequestOptions localVarRequestOptions = new Nomad.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };


            var localVarContentType = Nomad.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Nomad.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (region != null)
            {
                localVarRequestOptions.QueryParameters.Add(Nomad.Client.Client.ClientUtils.ParameterToMultiMap("", "region", region));
            }
            if (_namespace != null)
            {
                localVarRequestOptions.QueryParameters.Add(Nomad.Client.Client.ClientUtils.ParameterToMultiMap("", "namespace", _namespace));
            }
            if (idempotencyToken != null)
            {
                localVarRequestOptions.QueryParameters.Add(Nomad.Client.Client.ClientUtils.ParameterToMultiMap("", "idempotency_token", idempotencyToken));
            }
            if (xNomadToken != null)
            {
                localVarRequestOptions.HeaderParameters.Add("X-Nomad-Token", Nomad.Client.Client.ClientUtils.ParameterToString(xNomadToken)); // header parameter
            }

            // authentication (X-Nomad-Token) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Nomad-Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-Nomad-Token", this.Configuration.GetApiKeyWithPrefix("X-Nomad-Token"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<Object>("/namespace", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateNamespace", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Nomad.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="namespaceName">The namespace identifier.</param>
        /// <param name="region">Filters results based on the specified region. (optional)</param>
        /// <param name="_namespace">Filters results based on the specified namespace. (optional)</param>
        /// <param name="xNomadToken">A Nomad ACL token. (optional)</param>
        /// <param name="idempotencyToken">Can be used to ensure operations are only run once. (optional)</param>
        /// <returns></returns>
        public void DeleteNamespace(string namespaceName, string region = default(string), string _namespace = default(string), string xNomadToken = default(string), string idempotencyToken = default(string))
        {
            DeleteNamespaceWithHttpInfo(namespaceName, region, _namespace, xNomadToken, idempotencyToken);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Nomad.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="namespaceName">The namespace identifier.</param>
        /// <param name="region">Filters results based on the specified region. (optional)</param>
        /// <param name="_namespace">Filters results based on the specified namespace. (optional)</param>
        /// <param name="xNomadToken">A Nomad ACL token. (optional)</param>
        /// <param name="idempotencyToken">Can be used to ensure operations are only run once. (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public Nomad.Client.Client.ApiResponse<Object> DeleteNamespaceWithHttpInfo(string namespaceName, string region = default(string), string _namespace = default(string), string xNomadToken = default(string), string idempotencyToken = default(string))
        {
            // verify the required parameter 'namespaceName' is set
            if (namespaceName == null)
                throw new Nomad.Client.Client.ApiException(400, "Missing required parameter 'namespaceName' when calling NamespacesApi->DeleteNamespace");

            Nomad.Client.Client.RequestOptions localVarRequestOptions = new Nomad.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };

            var localVarContentType = Nomad.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Nomad.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("namespaceName", Nomad.Client.Client.ClientUtils.ParameterToString(namespaceName)); // path parameter
            if (region != null)
            {
                localVarRequestOptions.QueryParameters.Add(Nomad.Client.Client.ClientUtils.ParameterToMultiMap("", "region", region));
            }
            if (_namespace != null)
            {
                localVarRequestOptions.QueryParameters.Add(Nomad.Client.Client.ClientUtils.ParameterToMultiMap("", "namespace", _namespace));
            }
            if (idempotencyToken != null)
            {
                localVarRequestOptions.QueryParameters.Add(Nomad.Client.Client.ClientUtils.ParameterToMultiMap("", "idempotency_token", idempotencyToken));
            }
            if (xNomadToken != null)
            {
                localVarRequestOptions.HeaderParameters.Add("X-Nomad-Token", Nomad.Client.Client.ClientUtils.ParameterToString(xNomadToken)); // header parameter
            }

            // authentication (X-Nomad-Token) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Nomad-Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-Nomad-Token", this.Configuration.GetApiKeyWithPrefix("X-Nomad-Token"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Delete<Object>("/namespace/{namespaceName}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteNamespace", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Nomad.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="namespaceName">The namespace identifier.</param>
        /// <param name="region">Filters results based on the specified region. (optional)</param>
        /// <param name="_namespace">Filters results based on the specified namespace. (optional)</param>
        /// <param name="xNomadToken">A Nomad ACL token. (optional)</param>
        /// <param name="idempotencyToken">Can be used to ensure operations are only run once. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task DeleteNamespaceAsync(string namespaceName, string region = default(string), string _namespace = default(string), string xNomadToken = default(string), string idempotencyToken = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            await DeleteNamespaceWithHttpInfoAsync(namespaceName, region, _namespace, xNomadToken, idempotencyToken, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Nomad.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="namespaceName">The namespace identifier.</param>
        /// <param name="region">Filters results based on the specified region. (optional)</param>
        /// <param name="_namespace">Filters results based on the specified namespace. (optional)</param>
        /// <param name="xNomadToken">A Nomad ACL token. (optional)</param>
        /// <param name="idempotencyToken">Can be used to ensure operations are only run once. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Nomad.Client.Client.ApiResponse<Object>> DeleteNamespaceWithHttpInfoAsync(string namespaceName, string region = default(string), string _namespace = default(string), string xNomadToken = default(string), string idempotencyToken = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'namespaceName' is set
            if (namespaceName == null)
                throw new Nomad.Client.Client.ApiException(400, "Missing required parameter 'namespaceName' when calling NamespacesApi->DeleteNamespace");


            Nomad.Client.Client.RequestOptions localVarRequestOptions = new Nomad.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };


            var localVarContentType = Nomad.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Nomad.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("namespaceName", Nomad.Client.Client.ClientUtils.ParameterToString(namespaceName)); // path parameter
            if (region != null)
            {
                localVarRequestOptions.QueryParameters.Add(Nomad.Client.Client.ClientUtils.ParameterToMultiMap("", "region", region));
            }
            if (_namespace != null)
            {
                localVarRequestOptions.QueryParameters.Add(Nomad.Client.Client.ClientUtils.ParameterToMultiMap("", "namespace", _namespace));
            }
            if (idempotencyToken != null)
            {
                localVarRequestOptions.QueryParameters.Add(Nomad.Client.Client.ClientUtils.ParameterToMultiMap("", "idempotency_token", idempotencyToken));
            }
            if (xNomadToken != null)
            {
                localVarRequestOptions.HeaderParameters.Add("X-Nomad-Token", Nomad.Client.Client.ClientUtils.ParameterToString(xNomadToken)); // header parameter
            }

            // authentication (X-Nomad-Token) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Nomad-Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-Nomad-Token", this.Configuration.GetApiKeyWithPrefix("X-Nomad-Token"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.DeleteAsync<Object>("/namespace/{namespaceName}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteNamespace", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Nomad.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="namespaceName">The namespace identifier.</param>
        /// <param name="region">Filters results based on the specified region. (optional)</param>
        /// <param name="_namespace">Filters results based on the specified namespace. (optional)</param>
        /// <param name="index">If set, wait until query exceeds given index. Must be provided with WaitParam. (optional)</param>
        /// <param name="wait">Provided with IndexParam to wait for change. (optional)</param>
        /// <param name="stale">If present, results will include stale reads. (optional)</param>
        /// <param name="prefix">Constrains results to jobs that start with the defined prefix (optional)</param>
        /// <param name="xNomadToken">A Nomad ACL token. (optional)</param>
        /// <param name="perPage">Maximum number of results to return. (optional)</param>
        /// <param name="nextToken">Indicates where to start paging for queries that support pagination. (optional)</param>
        /// <returns>Namespace</returns>
        public Namespace GetNamespace(string namespaceName, string region = default(string), string _namespace = default(string), int? index = default(int?), string wait = default(string), string stale = default(string), string prefix = default(string), string xNomadToken = default(string), int? perPage = default(int?), string nextToken = default(string))
        {
            Nomad.Client.Client.ApiResponse<Namespace> localVarResponse = GetNamespaceWithHttpInfo(namespaceName, region, _namespace, index, wait, stale, prefix, xNomadToken, perPage, nextToken);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Nomad.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="namespaceName">The namespace identifier.</param>
        /// <param name="region">Filters results based on the specified region. (optional)</param>
        /// <param name="_namespace">Filters results based on the specified namespace. (optional)</param>
        /// <param name="index">If set, wait until query exceeds given index. Must be provided with WaitParam. (optional)</param>
        /// <param name="wait">Provided with IndexParam to wait for change. (optional)</param>
        /// <param name="stale">If present, results will include stale reads. (optional)</param>
        /// <param name="prefix">Constrains results to jobs that start with the defined prefix (optional)</param>
        /// <param name="xNomadToken">A Nomad ACL token. (optional)</param>
        /// <param name="perPage">Maximum number of results to return. (optional)</param>
        /// <param name="nextToken">Indicates where to start paging for queries that support pagination. (optional)</param>
        /// <returns>ApiResponse of Namespace</returns>
        public Nomad.Client.Client.ApiResponse<Namespace> GetNamespaceWithHttpInfo(string namespaceName, string region = default(string), string _namespace = default(string), int? index = default(int?), string wait = default(string), string stale = default(string), string prefix = default(string), string xNomadToken = default(string), int? perPage = default(int?), string nextToken = default(string))
        {
            // verify the required parameter 'namespaceName' is set
            if (namespaceName == null)
                throw new Nomad.Client.Client.ApiException(400, "Missing required parameter 'namespaceName' when calling NamespacesApi->GetNamespace");

            Nomad.Client.Client.RequestOptions localVarRequestOptions = new Nomad.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Nomad.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Nomad.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("namespaceName", Nomad.Client.Client.ClientUtils.ParameterToString(namespaceName)); // path parameter
            if (region != null)
            {
                localVarRequestOptions.QueryParameters.Add(Nomad.Client.Client.ClientUtils.ParameterToMultiMap("", "region", region));
            }
            if (_namespace != null)
            {
                localVarRequestOptions.QueryParameters.Add(Nomad.Client.Client.ClientUtils.ParameterToMultiMap("", "namespace", _namespace));
            }
            if (wait != null)
            {
                localVarRequestOptions.QueryParameters.Add(Nomad.Client.Client.ClientUtils.ParameterToMultiMap("", "wait", wait));
            }
            if (stale != null)
            {
                localVarRequestOptions.QueryParameters.Add(Nomad.Client.Client.ClientUtils.ParameterToMultiMap("", "stale", stale));
            }
            if (prefix != null)
            {
                localVarRequestOptions.QueryParameters.Add(Nomad.Client.Client.ClientUtils.ParameterToMultiMap("", "prefix", prefix));
            }
            if (perPage != null)
            {
                localVarRequestOptions.QueryParameters.Add(Nomad.Client.Client.ClientUtils.ParameterToMultiMap("", "per_page", perPage));
            }
            if (nextToken != null)
            {
                localVarRequestOptions.QueryParameters.Add(Nomad.Client.Client.ClientUtils.ParameterToMultiMap("", "next_token", nextToken));
            }
            if (index != null)
            {
                localVarRequestOptions.HeaderParameters.Add("index", Nomad.Client.Client.ClientUtils.ParameterToString(index)); // header parameter
            }
            if (xNomadToken != null)
            {
                localVarRequestOptions.HeaderParameters.Add("X-Nomad-Token", Nomad.Client.Client.ClientUtils.ParameterToString(xNomadToken)); // header parameter
            }

            // authentication (X-Nomad-Token) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Nomad-Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-Nomad-Token", this.Configuration.GetApiKeyWithPrefix("X-Nomad-Token"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<Namespace>("/namespace/{namespaceName}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetNamespace", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Nomad.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="namespaceName">The namespace identifier.</param>
        /// <param name="region">Filters results based on the specified region. (optional)</param>
        /// <param name="_namespace">Filters results based on the specified namespace. (optional)</param>
        /// <param name="index">If set, wait until query exceeds given index. Must be provided with WaitParam. (optional)</param>
        /// <param name="wait">Provided with IndexParam to wait for change. (optional)</param>
        /// <param name="stale">If present, results will include stale reads. (optional)</param>
        /// <param name="prefix">Constrains results to jobs that start with the defined prefix (optional)</param>
        /// <param name="xNomadToken">A Nomad ACL token. (optional)</param>
        /// <param name="perPage">Maximum number of results to return. (optional)</param>
        /// <param name="nextToken">Indicates where to start paging for queries that support pagination. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Namespace</returns>
        public async System.Threading.Tasks.Task<Namespace> GetNamespaceAsync(string namespaceName, string region = default(string), string _namespace = default(string), int? index = default(int?), string wait = default(string), string stale = default(string), string prefix = default(string), string xNomadToken = default(string), int? perPage = default(int?), string nextToken = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Nomad.Client.Client.ApiResponse<Namespace> localVarResponse = await GetNamespaceWithHttpInfoAsync(namespaceName, region, _namespace, index, wait, stale, prefix, xNomadToken, perPage, nextToken, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Nomad.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="namespaceName">The namespace identifier.</param>
        /// <param name="region">Filters results based on the specified region. (optional)</param>
        /// <param name="_namespace">Filters results based on the specified namespace. (optional)</param>
        /// <param name="index">If set, wait until query exceeds given index. Must be provided with WaitParam. (optional)</param>
        /// <param name="wait">Provided with IndexParam to wait for change. (optional)</param>
        /// <param name="stale">If present, results will include stale reads. (optional)</param>
        /// <param name="prefix">Constrains results to jobs that start with the defined prefix (optional)</param>
        /// <param name="xNomadToken">A Nomad ACL token. (optional)</param>
        /// <param name="perPage">Maximum number of results to return. (optional)</param>
        /// <param name="nextToken">Indicates where to start paging for queries that support pagination. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Namespace)</returns>
        public async System.Threading.Tasks.Task<Nomad.Client.Client.ApiResponse<Namespace>> GetNamespaceWithHttpInfoAsync(string namespaceName, string region = default(string), string _namespace = default(string), int? index = default(int?), string wait = default(string), string stale = default(string), string prefix = default(string), string xNomadToken = default(string), int? perPage = default(int?), string nextToken = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'namespaceName' is set
            if (namespaceName == null)
                throw new Nomad.Client.Client.ApiException(400, "Missing required parameter 'namespaceName' when calling NamespacesApi->GetNamespace");


            Nomad.Client.Client.RequestOptions localVarRequestOptions = new Nomad.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Nomad.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Nomad.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("namespaceName", Nomad.Client.Client.ClientUtils.ParameterToString(namespaceName)); // path parameter
            if (region != null)
            {
                localVarRequestOptions.QueryParameters.Add(Nomad.Client.Client.ClientUtils.ParameterToMultiMap("", "region", region));
            }
            if (_namespace != null)
            {
                localVarRequestOptions.QueryParameters.Add(Nomad.Client.Client.ClientUtils.ParameterToMultiMap("", "namespace", _namespace));
            }
            if (wait != null)
            {
                localVarRequestOptions.QueryParameters.Add(Nomad.Client.Client.ClientUtils.ParameterToMultiMap("", "wait", wait));
            }
            if (stale != null)
            {
                localVarRequestOptions.QueryParameters.Add(Nomad.Client.Client.ClientUtils.ParameterToMultiMap("", "stale", stale));
            }
            if (prefix != null)
            {
                localVarRequestOptions.QueryParameters.Add(Nomad.Client.Client.ClientUtils.ParameterToMultiMap("", "prefix", prefix));
            }
            if (perPage != null)
            {
                localVarRequestOptions.QueryParameters.Add(Nomad.Client.Client.ClientUtils.ParameterToMultiMap("", "per_page", perPage));
            }
            if (nextToken != null)
            {
                localVarRequestOptions.QueryParameters.Add(Nomad.Client.Client.ClientUtils.ParameterToMultiMap("", "next_token", nextToken));
            }
            if (index != null)
            {
                localVarRequestOptions.HeaderParameters.Add("index", Nomad.Client.Client.ClientUtils.ParameterToString(index)); // header parameter
            }
            if (xNomadToken != null)
            {
                localVarRequestOptions.HeaderParameters.Add("X-Nomad-Token", Nomad.Client.Client.ClientUtils.ParameterToString(xNomadToken)); // header parameter
            }

            // authentication (X-Nomad-Token) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Nomad-Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-Nomad-Token", this.Configuration.GetApiKeyWithPrefix("X-Nomad-Token"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<Namespace>("/namespace/{namespaceName}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetNamespace", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Nomad.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="region">Filters results based on the specified region. (optional)</param>
        /// <param name="_namespace">Filters results based on the specified namespace. (optional)</param>
        /// <param name="index">If set, wait until query exceeds given index. Must be provided with WaitParam. (optional)</param>
        /// <param name="wait">Provided with IndexParam to wait for change. (optional)</param>
        /// <param name="stale">If present, results will include stale reads. (optional)</param>
        /// <param name="prefix">Constrains results to jobs that start with the defined prefix (optional)</param>
        /// <param name="xNomadToken">A Nomad ACL token. (optional)</param>
        /// <param name="perPage">Maximum number of results to return. (optional)</param>
        /// <param name="nextToken">Indicates where to start paging for queries that support pagination. (optional)</param>
        /// <returns>List&lt;Namespace&gt;</returns>
        public List<Namespace> GetNamespaces(string region = default(string), string _namespace = default(string), int? index = default(int?), string wait = default(string), string stale = default(string), string prefix = default(string), string xNomadToken = default(string), int? perPage = default(int?), string nextToken = default(string))
        {
            Nomad.Client.Client.ApiResponse<List<Namespace>> localVarResponse = GetNamespacesWithHttpInfo(region, _namespace, index, wait, stale, prefix, xNomadToken, perPage, nextToken);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Nomad.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="region">Filters results based on the specified region. (optional)</param>
        /// <param name="_namespace">Filters results based on the specified namespace. (optional)</param>
        /// <param name="index">If set, wait until query exceeds given index. Must be provided with WaitParam. (optional)</param>
        /// <param name="wait">Provided with IndexParam to wait for change. (optional)</param>
        /// <param name="stale">If present, results will include stale reads. (optional)</param>
        /// <param name="prefix">Constrains results to jobs that start with the defined prefix (optional)</param>
        /// <param name="xNomadToken">A Nomad ACL token. (optional)</param>
        /// <param name="perPage">Maximum number of results to return. (optional)</param>
        /// <param name="nextToken">Indicates where to start paging for queries that support pagination. (optional)</param>
        /// <returns>ApiResponse of List&lt;Namespace&gt;</returns>
        public Nomad.Client.Client.ApiResponse<List<Namespace>> GetNamespacesWithHttpInfo(string region = default(string), string _namespace = default(string), int? index = default(int?), string wait = default(string), string stale = default(string), string prefix = default(string), string xNomadToken = default(string), int? perPage = default(int?), string nextToken = default(string))
        {
            Nomad.Client.Client.RequestOptions localVarRequestOptions = new Nomad.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Nomad.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Nomad.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (region != null)
            {
                localVarRequestOptions.QueryParameters.Add(Nomad.Client.Client.ClientUtils.ParameterToMultiMap("", "region", region));
            }
            if (_namespace != null)
            {
                localVarRequestOptions.QueryParameters.Add(Nomad.Client.Client.ClientUtils.ParameterToMultiMap("", "namespace", _namespace));
            }
            if (wait != null)
            {
                localVarRequestOptions.QueryParameters.Add(Nomad.Client.Client.ClientUtils.ParameterToMultiMap("", "wait", wait));
            }
            if (stale != null)
            {
                localVarRequestOptions.QueryParameters.Add(Nomad.Client.Client.ClientUtils.ParameterToMultiMap("", "stale", stale));
            }
            if (prefix != null)
            {
                localVarRequestOptions.QueryParameters.Add(Nomad.Client.Client.ClientUtils.ParameterToMultiMap("", "prefix", prefix));
            }
            if (perPage != null)
            {
                localVarRequestOptions.QueryParameters.Add(Nomad.Client.Client.ClientUtils.ParameterToMultiMap("", "per_page", perPage));
            }
            if (nextToken != null)
            {
                localVarRequestOptions.QueryParameters.Add(Nomad.Client.Client.ClientUtils.ParameterToMultiMap("", "next_token", nextToken));
            }
            if (index != null)
            {
                localVarRequestOptions.HeaderParameters.Add("index", Nomad.Client.Client.ClientUtils.ParameterToString(index)); // header parameter
            }
            if (xNomadToken != null)
            {
                localVarRequestOptions.HeaderParameters.Add("X-Nomad-Token", Nomad.Client.Client.ClientUtils.ParameterToString(xNomadToken)); // header parameter
            }

            // authentication (X-Nomad-Token) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Nomad-Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-Nomad-Token", this.Configuration.GetApiKeyWithPrefix("X-Nomad-Token"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<List<Namespace>>("/namespaces", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetNamespaces", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Nomad.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="region">Filters results based on the specified region. (optional)</param>
        /// <param name="_namespace">Filters results based on the specified namespace. (optional)</param>
        /// <param name="index">If set, wait until query exceeds given index. Must be provided with WaitParam. (optional)</param>
        /// <param name="wait">Provided with IndexParam to wait for change. (optional)</param>
        /// <param name="stale">If present, results will include stale reads. (optional)</param>
        /// <param name="prefix">Constrains results to jobs that start with the defined prefix (optional)</param>
        /// <param name="xNomadToken">A Nomad ACL token. (optional)</param>
        /// <param name="perPage">Maximum number of results to return. (optional)</param>
        /// <param name="nextToken">Indicates where to start paging for queries that support pagination. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;Namespace&gt;</returns>
        public async System.Threading.Tasks.Task<List<Namespace>> GetNamespacesAsync(string region = default(string), string _namespace = default(string), int? index = default(int?), string wait = default(string), string stale = default(string), string prefix = default(string), string xNomadToken = default(string), int? perPage = default(int?), string nextToken = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Nomad.Client.Client.ApiResponse<List<Namespace>> localVarResponse = await GetNamespacesWithHttpInfoAsync(region, _namespace, index, wait, stale, prefix, xNomadToken, perPage, nextToken, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Nomad.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="region">Filters results based on the specified region. (optional)</param>
        /// <param name="_namespace">Filters results based on the specified namespace. (optional)</param>
        /// <param name="index">If set, wait until query exceeds given index. Must be provided with WaitParam. (optional)</param>
        /// <param name="wait">Provided with IndexParam to wait for change. (optional)</param>
        /// <param name="stale">If present, results will include stale reads. (optional)</param>
        /// <param name="prefix">Constrains results to jobs that start with the defined prefix (optional)</param>
        /// <param name="xNomadToken">A Nomad ACL token. (optional)</param>
        /// <param name="perPage">Maximum number of results to return. (optional)</param>
        /// <param name="nextToken">Indicates where to start paging for queries that support pagination. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;Namespace&gt;)</returns>
        public async System.Threading.Tasks.Task<Nomad.Client.Client.ApiResponse<List<Namespace>>> GetNamespacesWithHttpInfoAsync(string region = default(string), string _namespace = default(string), int? index = default(int?), string wait = default(string), string stale = default(string), string prefix = default(string), string xNomadToken = default(string), int? perPage = default(int?), string nextToken = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Nomad.Client.Client.RequestOptions localVarRequestOptions = new Nomad.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Nomad.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Nomad.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (region != null)
            {
                localVarRequestOptions.QueryParameters.Add(Nomad.Client.Client.ClientUtils.ParameterToMultiMap("", "region", region));
            }
            if (_namespace != null)
            {
                localVarRequestOptions.QueryParameters.Add(Nomad.Client.Client.ClientUtils.ParameterToMultiMap("", "namespace", _namespace));
            }
            if (wait != null)
            {
                localVarRequestOptions.QueryParameters.Add(Nomad.Client.Client.ClientUtils.ParameterToMultiMap("", "wait", wait));
            }
            if (stale != null)
            {
                localVarRequestOptions.QueryParameters.Add(Nomad.Client.Client.ClientUtils.ParameterToMultiMap("", "stale", stale));
            }
            if (prefix != null)
            {
                localVarRequestOptions.QueryParameters.Add(Nomad.Client.Client.ClientUtils.ParameterToMultiMap("", "prefix", prefix));
            }
            if (perPage != null)
            {
                localVarRequestOptions.QueryParameters.Add(Nomad.Client.Client.ClientUtils.ParameterToMultiMap("", "per_page", perPage));
            }
            if (nextToken != null)
            {
                localVarRequestOptions.QueryParameters.Add(Nomad.Client.Client.ClientUtils.ParameterToMultiMap("", "next_token", nextToken));
            }
            if (index != null)
            {
                localVarRequestOptions.HeaderParameters.Add("index", Nomad.Client.Client.ClientUtils.ParameterToString(index)); // header parameter
            }
            if (xNomadToken != null)
            {
                localVarRequestOptions.HeaderParameters.Add("X-Nomad-Token", Nomad.Client.Client.ClientUtils.ParameterToString(xNomadToken)); // header parameter
            }

            // authentication (X-Nomad-Token) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Nomad-Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-Nomad-Token", this.Configuration.GetApiKeyWithPrefix("X-Nomad-Token"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<List<Namespace>>("/namespaces", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetNamespaces", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Nomad.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="namespaceName">The namespace identifier.</param>
        /// <param name="_namespace2"></param>
        /// <param name="region">Filters results based on the specified region. (optional)</param>
        /// <param name="_namespace">Filters results based on the specified namespace. (optional)</param>
        /// <param name="xNomadToken">A Nomad ACL token. (optional)</param>
        /// <param name="idempotencyToken">Can be used to ensure operations are only run once. (optional)</param>
        /// <returns></returns>
        public void PostNamespace(string namespaceName, Namespace _namespace2, string region = default(string), string _namespace = default(string), string xNomadToken = default(string), string idempotencyToken = default(string))
        {
            PostNamespaceWithHttpInfo(namespaceName, _namespace2, region, _namespace, xNomadToken, idempotencyToken);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Nomad.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="namespaceName">The namespace identifier.</param>
        /// <param name="_namespace2"></param>
        /// <param name="region">Filters results based on the specified region. (optional)</param>
        /// <param name="_namespace">Filters results based on the specified namespace. (optional)</param>
        /// <param name="xNomadToken">A Nomad ACL token. (optional)</param>
        /// <param name="idempotencyToken">Can be used to ensure operations are only run once. (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public Nomad.Client.Client.ApiResponse<Object> PostNamespaceWithHttpInfo(string namespaceName, Namespace _namespace2, string region = default(string), string _namespace = default(string), string xNomadToken = default(string), string idempotencyToken = default(string))
        {
            // verify the required parameter 'namespaceName' is set
            if (namespaceName == null)
                throw new Nomad.Client.Client.ApiException(400, "Missing required parameter 'namespaceName' when calling NamespacesApi->PostNamespace");

            // verify the required parameter '_namespace2' is set
            if (_namespace2 == null)
                throw new Nomad.Client.Client.ApiException(400, "Missing required parameter '_namespace2' when calling NamespacesApi->PostNamespace");

            Nomad.Client.Client.RequestOptions localVarRequestOptions = new Nomad.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };

            var localVarContentType = Nomad.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Nomad.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("namespaceName", Nomad.Client.Client.ClientUtils.ParameterToString(namespaceName)); // path parameter
            if (region != null)
            {
                localVarRequestOptions.QueryParameters.Add(Nomad.Client.Client.ClientUtils.ParameterToMultiMap("", "region", region));
            }
            if (_namespace != null)
            {
                localVarRequestOptions.QueryParameters.Add(Nomad.Client.Client.ClientUtils.ParameterToMultiMap("", "namespace", _namespace));
            }
            if (idempotencyToken != null)
            {
                localVarRequestOptions.QueryParameters.Add(Nomad.Client.Client.ClientUtils.ParameterToMultiMap("", "idempotency_token", idempotencyToken));
            }
            if (xNomadToken != null)
            {
                localVarRequestOptions.HeaderParameters.Add("X-Nomad-Token", Nomad.Client.Client.ClientUtils.ParameterToString(xNomadToken)); // header parameter
            }
            localVarRequestOptions.Data = _namespace2;

            // authentication (X-Nomad-Token) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Nomad-Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-Nomad-Token", this.Configuration.GetApiKeyWithPrefix("X-Nomad-Token"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<Object>("/namespace/{namespaceName}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PostNamespace", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Nomad.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="namespaceName">The namespace identifier.</param>
        /// <param name="_namespace2"></param>
        /// <param name="region">Filters results based on the specified region. (optional)</param>
        /// <param name="_namespace">Filters results based on the specified namespace. (optional)</param>
        /// <param name="xNomadToken">A Nomad ACL token. (optional)</param>
        /// <param name="idempotencyToken">Can be used to ensure operations are only run once. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task PostNamespaceAsync(string namespaceName, Namespace _namespace2, string region = default(string), string _namespace = default(string), string xNomadToken = default(string), string idempotencyToken = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            await PostNamespaceWithHttpInfoAsync(namespaceName, _namespace2, region, _namespace, xNomadToken, idempotencyToken, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Nomad.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="namespaceName">The namespace identifier.</param>
        /// <param name="_namespace2"></param>
        /// <param name="region">Filters results based on the specified region. (optional)</param>
        /// <param name="_namespace">Filters results based on the specified namespace. (optional)</param>
        /// <param name="xNomadToken">A Nomad ACL token. (optional)</param>
        /// <param name="idempotencyToken">Can be used to ensure operations are only run once. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Nomad.Client.Client.ApiResponse<Object>> PostNamespaceWithHttpInfoAsync(string namespaceName, Namespace _namespace2, string region = default(string), string _namespace = default(string), string xNomadToken = default(string), string idempotencyToken = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'namespaceName' is set
            if (namespaceName == null)
                throw new Nomad.Client.Client.ApiException(400, "Missing required parameter 'namespaceName' when calling NamespacesApi->PostNamespace");

            // verify the required parameter '_namespace2' is set
            if (_namespace2 == null)
                throw new Nomad.Client.Client.ApiException(400, "Missing required parameter '_namespace2' when calling NamespacesApi->PostNamespace");


            Nomad.Client.Client.RequestOptions localVarRequestOptions = new Nomad.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };


            var localVarContentType = Nomad.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Nomad.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("namespaceName", Nomad.Client.Client.ClientUtils.ParameterToString(namespaceName)); // path parameter
            if (region != null)
            {
                localVarRequestOptions.QueryParameters.Add(Nomad.Client.Client.ClientUtils.ParameterToMultiMap("", "region", region));
            }
            if (_namespace != null)
            {
                localVarRequestOptions.QueryParameters.Add(Nomad.Client.Client.ClientUtils.ParameterToMultiMap("", "namespace", _namespace));
            }
            if (idempotencyToken != null)
            {
                localVarRequestOptions.QueryParameters.Add(Nomad.Client.Client.ClientUtils.ParameterToMultiMap("", "idempotency_token", idempotencyToken));
            }
            if (xNomadToken != null)
            {
                localVarRequestOptions.HeaderParameters.Add("X-Nomad-Token", Nomad.Client.Client.ClientUtils.ParameterToString(xNomadToken)); // header parameter
            }
            localVarRequestOptions.Data = _namespace2;

            // authentication (X-Nomad-Token) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Nomad-Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-Nomad-Token", this.Configuration.GetApiKeyWithPrefix("X-Nomad-Token"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<Object>("/namespace/{namespaceName}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PostNamespace", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
