/*
 * Nomad
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.nomadproject.client.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for JobDispatchResponse
 */
public class JobDispatchResponseTest {
    private final JobDispatchResponse model = new JobDispatchResponse();

    /**
     * Model tests for JobDispatchResponse
     */
    @Test
    public void testJobDispatchResponse() {
        // TODO: test JobDispatchResponse
    }

    /**
     * Test the property 'dispatchedJobID'
     */
    @Test
    public void dispatchedJobIDTest() {
        // TODO: test dispatchedJobID
    }

    /**
     * Test the property 'evalCreateIndex'
     */
    @Test
    public void evalCreateIndexTest() {
        // TODO: test evalCreateIndex
    }

    /**
     * Test the property 'evalID'
     */
    @Test
    public void evalIDTest() {
        // TODO: test evalID
    }

    /**
     * Test the property 'jobCreateIndex'
     */
    @Test
    public void jobCreateIndexTest() {
        // TODO: test jobCreateIndex
    }

    /**
     * Test the property 'lastIndex'
     */
    @Test
    public void lastIndexTest() {
        // TODO: test lastIndex
    }

    /**
     * Test the property 'requestTime'
     */
    @Test
    public void requestTimeTest() {
        // TODO: test requestTime
    }

}
