/*
 * Nomad
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.nomadproject.client.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.nomadproject.client.models.CSIInfo;
import io.nomadproject.client.models.DrainMetadata;
import io.nomadproject.client.models.DrainStrategy;
import io.nomadproject.client.models.DriverInfo;
import io.nomadproject.client.models.HostNetworkInfo;
import io.nomadproject.client.models.HostVolumeInfo;
import io.nomadproject.client.models.NodeEvent;
import io.nomadproject.client.models.NodeReservedResources;
import io.nomadproject.client.models.NodeResources;
import io.nomadproject.client.models.Resources;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Node
 */
public class NodeTest {
    private final Node model = new Node();

    /**
     * Model tests for Node
     */
    @Test
    public void testNode() {
        // TODO: test Node
    }

    /**
     * Test the property 'attributes'
     */
    @Test
    public void attributesTest() {
        // TODO: test attributes
    }

    /**
     * Test the property 'csIControllerPlugins'
     */
    @Test
    public void csIControllerPluginsTest() {
        // TODO: test csIControllerPlugins
    }

    /**
     * Test the property 'csINodePlugins'
     */
    @Test
    public void csINodePluginsTest() {
        // TODO: test csINodePlugins
    }

    /**
     * Test the property 'cgroupParent'
     */
    @Test
    public void cgroupParentTest() {
        // TODO: test cgroupParent
    }

    /**
     * Test the property 'createIndex'
     */
    @Test
    public void createIndexTest() {
        // TODO: test createIndex
    }

    /**
     * Test the property 'datacenter'
     */
    @Test
    public void datacenterTest() {
        // TODO: test datacenter
    }

    /**
     * Test the property 'drain'
     */
    @Test
    public void drainTest() {
        // TODO: test drain
    }

    /**
     * Test the property 'drainStrategy'
     */
    @Test
    public void drainStrategyTest() {
        // TODO: test drainStrategy
    }

    /**
     * Test the property 'drivers'
     */
    @Test
    public void driversTest() {
        // TODO: test drivers
    }

    /**
     * Test the property 'events'
     */
    @Test
    public void eventsTest() {
        // TODO: test events
    }

    /**
     * Test the property 'htTPAddr'
     */
    @Test
    public void htTPAddrTest() {
        // TODO: test htTPAddr
    }

    /**
     * Test the property 'hostNetworks'
     */
    @Test
    public void hostNetworksTest() {
        // TODO: test hostNetworks
    }

    /**
     * Test the property 'hostVolumes'
     */
    @Test
    public void hostVolumesTest() {
        // TODO: test hostVolumes
    }

    /**
     * Test the property 'ID'
     */
    @Test
    public void IDTest() {
        // TODO: test ID
    }

    /**
     * Test the property 'lastDrain'
     */
    @Test
    public void lastDrainTest() {
        // TODO: test lastDrain
    }

    /**
     * Test the property 'links'
     */
    @Test
    public void linksTest() {
        // TODO: test links
    }

    /**
     * Test the property 'meta'
     */
    @Test
    public void metaTest() {
        // TODO: test meta
    }

    /**
     * Test the property 'modifyIndex'
     */
    @Test
    public void modifyIndexTest() {
        // TODO: test modifyIndex
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'nodeClass'
     */
    @Test
    public void nodeClassTest() {
        // TODO: test nodeClass
    }

    /**
     * Test the property 'nodeResources'
     */
    @Test
    public void nodeResourcesTest() {
        // TODO: test nodeResources
    }

    /**
     * Test the property 'reserved'
     */
    @Test
    public void reservedTest() {
        // TODO: test reserved
    }

    /**
     * Test the property 'reservedResources'
     */
    @Test
    public void reservedResourcesTest() {
        // TODO: test reservedResources
    }

    /**
     * Test the property 'resources'
     */
    @Test
    public void resourcesTest() {
        // TODO: test resources
    }

    /**
     * Test the property 'schedulingEligibility'
     */
    @Test
    public void schedulingEligibilityTest() {
        // TODO: test schedulingEligibility
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'statusDescription'
     */
    @Test
    public void statusDescriptionTest() {
        // TODO: test statusDescription
    }

    /**
     * Test the property 'statusUpdatedAt'
     */
    @Test
    public void statusUpdatedAtTest() {
        // TODO: test statusUpdatedAt
    }

    /**
     * Test the property 'tlSEnabled'
     */
    @Test
    public void tlSEnabledTest() {
        // TODO: test tlSEnabled
    }

}
