/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.1.3
 * Contact: support@hashicorp.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

type Allocation struct {
	AllocModifyIndex int32 `json:"AllocModifyIndex,omitempty"`

	AllocatedResources AllocatedResources `json:"AllocatedResources,omitempty"`

	ClientDescription string `json:"ClientDescription,omitempty"`

	ClientStatus string `json:"ClientStatus,omitempty"`

	CreateIndex int32 `json:"CreateIndex,omitempty"`

	CreateTime int64 `json:"CreateTime,omitempty"`

	DeploymentID string `json:"DeploymentID,omitempty"`

	DeploymentStatus AllocDeploymentStatus `json:"DeploymentStatus,omitempty"`

	DesiredDescription string `json:"DesiredDescription,omitempty"`

	DesiredStatus string `json:"DesiredStatus,omitempty"`

	DesiredTransition DesiredTransition `json:"DesiredTransition,omitempty"`

	EvalID string `json:"EvalID,omitempty"`

	FollowupEvalID string `json:"FollowupEvalID,omitempty"`

	ID string `json:"ID,omitempty"`

	Job Job `json:"Job,omitempty"`

	JobID string `json:"JobID,omitempty"`

	Metrics AllocationMetric `json:"Metrics,omitempty"`

	ModifyIndex int32 `json:"ModifyIndex,omitempty"`

	ModifyTime int64 `json:"ModifyTime,omitempty"`

	Name string `json:"Name,omitempty"`

	Namespace string `json:"Namespace,omitempty"`

	NextAllocation string `json:"NextAllocation,omitempty"`

	NodeID string `json:"NodeID,omitempty"`

	NodeName string `json:"NodeName,omitempty"`

	PreemptedAllocations []string `json:"PreemptedAllocations,omitempty"`

	PreemptedByAllocation string `json:"PreemptedByAllocation,omitempty"`

	PreviousAllocation string `json:"PreviousAllocation,omitempty"`

	RescheduleTracker RescheduleTracker `json:"RescheduleTracker,omitempty"`

	Resources Resources `json:"Resources,omitempty"`

	Services map[string]string `json:"Services,omitempty"`

	TaskGroup string `json:"TaskGroup,omitempty"`

	TaskResources map[string]Resources `json:"TaskResources,omitempty"`

	TaskStates map[string]TaskState `json:"TaskStates,omitempty"`
}
