/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.1.3
 * Contact: support@hashicorp.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

type GaugeValue struct {
	Labels map[string]string `json:"Labels,omitempty"`

	Name string `json:"Name,omitempty"`

	Value float32 `json:"Value,omitempty"`
}
