"""
    Nomad

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.1.4
    Contact: support@hashicorp.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.drain_metadata import DrainMetadata


class TestDrainMetadata(unittest.TestCase):
    """DrainMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDrainMetadata(self):
        """Test DrainMetadata"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DrainMetadata()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
