"""
    Nomad

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.1.4
    Contact: support@hashicorp.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import nomad_client
from nomad_client.model.node_update_eligibility_request import NodeUpdateEligibilityRequest


class TestNodeUpdateEligibilityRequest(unittest.TestCase):
    """NodeUpdateEligibilityRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNodeUpdateEligibilityRequest(self):
        """Test NodeUpdateEligibilityRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NodeUpdateEligibilityRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
