"""
    Nomad

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.1.3
    Contact: support@hashicorp.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import nomad_client
from nomad_client.model.csi_secrets import CSISecrets
globals()['CSISecrets'] = CSISecrets
from nomad_client.model.csi_snapshot import CSISnapshot


class TestCSISnapshot(unittest.TestCase):
    """CSISnapshot unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCSISnapshot(self):
        """Test CSISnapshot"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CSISnapshot()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
