# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

"""
    Nomad

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.1.3
    Contact: support@hashicorp.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import nomad_client
from nomad_client.model.job_children_summary import JobChildrenSummary
from nomad_client.model.task_group_summary import TaskGroupSummary
globals()['JobChildrenSummary'] = JobChildrenSummary
globals()['TaskGroupSummary'] = TaskGroupSummary
from nomad_client.model.job_summary import JobSummary


class TestJobSummary(unittest.TestCase):
    """JobSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJobSummary(self):
        """Test JobSummary"""
        # FIXME: construct object with mandatory attributes with example values
        # model = JobSummary()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
