"""
    Nomad

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.1.4
    Contact: support@hashicorp.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import nomad_client
from nomad_client.model.csi_info import CSIInfo
from nomad_client.model.drain_metadata import DrainMetadata
from nomad_client.model.drain_strategy import DrainStrategy
from nomad_client.model.driver_info import DriverInfo
from nomad_client.model.host_volume_info import HostVolumeInfo
from nomad_client.model.node_event import NodeEvent
from nomad_client.model.node_reserved_resources import NodeReservedResources
from nomad_client.model.node_resources import NodeResources
from nomad_client.model.resources import Resources
globals()['CSIInfo'] = CSIInfo
globals()['DrainMetadata'] = DrainMetadata
globals()['DrainStrategy'] = DrainStrategy
globals()['DriverInfo'] = DriverInfo
globals()['HostVolumeInfo'] = HostVolumeInfo
globals()['NodeEvent'] = NodeEvent
globals()['NodeReservedResources'] = NodeReservedResources
globals()['NodeResources'] = NodeResources
globals()['Resources'] = Resources
from nomad_client.model.node import Node


class TestNode(unittest.TestCase):
    """Node unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNode(self):
        """Test Node"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Node()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
