/*
Nomad

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.1.4
Contact: support@hashicorp.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"time"
)

// DrainStrategy struct for DrainStrategy
type DrainStrategy struct {
	Deadline *int64 `json:"Deadline,omitempty"`
	ForceDeadline NullableTime `json:"ForceDeadline,omitempty"`
	IgnoreSystemJobs *bool `json:"IgnoreSystemJobs,omitempty"`
	StartedAt NullableTime `json:"StartedAt,omitempty"`
}

// NewDrainStrategy instantiates a new DrainStrategy object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDrainStrategy() *DrainStrategy {
	this := DrainStrategy{}
	return &this
}

// NewDrainStrategyWithDefaults instantiates a new DrainStrategy object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDrainStrategyWithDefaults() *DrainStrategy {
	this := DrainStrategy{}
	return &this
}

// GetDeadline returns the Deadline field value if set, zero value otherwise.
func (o *DrainStrategy) GetDeadline() int64 {
	if o == nil || o.Deadline == nil {
		var ret int64
		return ret
	}
	return *o.Deadline
}

// GetDeadlineOk returns a tuple with the Deadline field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DrainStrategy) GetDeadlineOk() (*int64, bool) {
	if o == nil || o.Deadline == nil {
		return nil, false
	}
	return o.Deadline, true
}

// HasDeadline returns a boolean if a field has been set.
func (o *DrainStrategy) HasDeadline() bool {
	if o != nil && o.Deadline != nil {
		return true
	}

	return false
}

// SetDeadline gets a reference to the given int64 and assigns it to the Deadline field.
func (o *DrainStrategy) SetDeadline(v int64) {
	o.Deadline = &v
}

// GetForceDeadline returns the ForceDeadline field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DrainStrategy) GetForceDeadline() time.Time {
	if o == nil || o.ForceDeadline.Get() == nil {
		var ret time.Time
		return ret
	}
	return *o.ForceDeadline.Get()
}

// GetForceDeadlineOk returns a tuple with the ForceDeadline field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DrainStrategy) GetForceDeadlineOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ForceDeadline.Get(), o.ForceDeadline.IsSet()
}

// HasForceDeadline returns a boolean if a field has been set.
func (o *DrainStrategy) HasForceDeadline() bool {
	if o != nil && o.ForceDeadline.IsSet() {
		return true
	}

	return false
}

// SetForceDeadline gets a reference to the given NullableTime and assigns it to the ForceDeadline field.
func (o *DrainStrategy) SetForceDeadline(v time.Time) {
	o.ForceDeadline.Set(&v)
}
// SetForceDeadlineNil sets the value for ForceDeadline to be an explicit nil
func (o *DrainStrategy) SetForceDeadlineNil() {
	o.ForceDeadline.Set(nil)
}

// UnsetForceDeadline ensures that no value is present for ForceDeadline, not even an explicit nil
func (o *DrainStrategy) UnsetForceDeadline() {
	o.ForceDeadline.Unset()
}

// GetIgnoreSystemJobs returns the IgnoreSystemJobs field value if set, zero value otherwise.
func (o *DrainStrategy) GetIgnoreSystemJobs() bool {
	if o == nil || o.IgnoreSystemJobs == nil {
		var ret bool
		return ret
	}
	return *o.IgnoreSystemJobs
}

// GetIgnoreSystemJobsOk returns a tuple with the IgnoreSystemJobs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DrainStrategy) GetIgnoreSystemJobsOk() (*bool, bool) {
	if o == nil || o.IgnoreSystemJobs == nil {
		return nil, false
	}
	return o.IgnoreSystemJobs, true
}

// HasIgnoreSystemJobs returns a boolean if a field has been set.
func (o *DrainStrategy) HasIgnoreSystemJobs() bool {
	if o != nil && o.IgnoreSystemJobs != nil {
		return true
	}

	return false
}

// SetIgnoreSystemJobs gets a reference to the given bool and assigns it to the IgnoreSystemJobs field.
func (o *DrainStrategy) SetIgnoreSystemJobs(v bool) {
	o.IgnoreSystemJobs = &v
}

// GetStartedAt returns the StartedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DrainStrategy) GetStartedAt() time.Time {
	if o == nil || o.StartedAt.Get() == nil {
		var ret time.Time
		return ret
	}
	return *o.StartedAt.Get()
}

// GetStartedAtOk returns a tuple with the StartedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DrainStrategy) GetStartedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.StartedAt.Get(), o.StartedAt.IsSet()
}

// HasStartedAt returns a boolean if a field has been set.
func (o *DrainStrategy) HasStartedAt() bool {
	if o != nil && o.StartedAt.IsSet() {
		return true
	}

	return false
}

// SetStartedAt gets a reference to the given NullableTime and assigns it to the StartedAt field.
func (o *DrainStrategy) SetStartedAt(v time.Time) {
	o.StartedAt.Set(&v)
}
// SetStartedAtNil sets the value for StartedAt to be an explicit nil
func (o *DrainStrategy) SetStartedAtNil() {
	o.StartedAt.Set(nil)
}

// UnsetStartedAt ensures that no value is present for StartedAt, not even an explicit nil
func (o *DrainStrategy) UnsetStartedAt() {
	o.StartedAt.Unset()
}

func (o DrainStrategy) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Deadline != nil {
		toSerialize["Deadline"] = o.Deadline
	}
	if o.ForceDeadline.IsSet() {
		toSerialize["ForceDeadline"] = o.ForceDeadline.Get()
	}
	if o.IgnoreSystemJobs != nil {
		toSerialize["IgnoreSystemJobs"] = o.IgnoreSystemJobs
	}
	if o.StartedAt.IsSet() {
		toSerialize["StartedAt"] = o.StartedAt.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableDrainStrategy struct {
	value *DrainStrategy
	isSet bool
}

func (v NullableDrainStrategy) Get() *DrainStrategy {
	return v.value
}

func (v *NullableDrainStrategy) Set(val *DrainStrategy) {
	v.value = val
	v.isSet = true
}

func (v NullableDrainStrategy) IsSet() bool {
	return v.isSet
}

func (v *NullableDrainStrategy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDrainStrategy(val *DrainStrategy) *NullableDrainStrategy {
	return &NullableDrainStrategy{value: val, isSet: true}
}

func (v NullableDrainStrategy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDrainStrategy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


