/**
 * Nomad
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.1.4
 * Contact: support@hashicorp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class TaskGroupSummary {
    'complete'?: number;
    'failed'?: number;
    'lost'?: number;
    'queued'?: number;
    'running'?: number;
    'starting'?: number;
    'unknown'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "complete",
            "baseName": "Complete",
            "type": "number",
            "format": ""
        },
        {
            "name": "failed",
            "baseName": "Failed",
            "type": "number",
            "format": ""
        },
        {
            "name": "lost",
            "baseName": "Lost",
            "type": "number",
            "format": ""
        },
        {
            "name": "queued",
            "baseName": "Queued",
            "type": "number",
            "format": ""
        },
        {
            "name": "running",
            "baseName": "Running",
            "type": "number",
            "format": ""
        },
        {
            "name": "starting",
            "baseName": "Starting",
            "type": "number",
            "format": ""
        },
        {
            "name": "unknown",
            "baseName": "Unknown",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TaskGroupSummary.attributeTypeMap;
    }

    public constructor() {
    }
}

