# File is used by the openapi-generator cli to generate a javascript client.
generatorName: javascript
gitUserId: hashicorp
gitRepoId: nomad-openapi/clients/javascript/v1
inputSpec: /local/v1/openapi.yaml
outputDir: /local/clients/javascript/v1
moduleName: nomad-client
projectVersion: 1.1.4
licenseName: Mozilla Public License 2.0